#!/usr/bin/env python3
"""Apply or simulate the delete_plan.csv produced by detect_duplicates.py

Usage:
  apply_delete_plan.py --delete-plan PATH [--dry-run] [--apply] [--backup-dir DIR] [--use-hardlink]

Behavior:
  - In dry-run mode (default) prints planned operations and exits with code 0.
  - With --apply: for each row it verifies files and sha256, moves the duplicate file to backup dir,
    creates a symlink at the original location pointing to the keep_path, and logs operations.
  - Creates a rollback script (apply_rollback.sh) to restore moved files.
"""
import argparse
import csv
import hashlib
import os
import shutil
import sys
from datetime import datetime


def sha256_of(path: str) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def ensure_parent(path: str) -> None:
    parent = os.path.dirname(path)
    if parent and not os.path.exists(parent):
        os.makedirs(parent, exist_ok=True)


def load_delete_plan(path: str):
    rows = []
    with open(path, newline='', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for r in reader:
            rows.append(r)
    return rows


def make_backup_path(base_backup_dir: str, original_path: str) -> str:
    # Preserve relative structure under backup dir
    # Avoid name collisions by mirroring path
    rel = original_path.lstrip(os.sep).replace(':', '')
    return os.path.join(base_backup_dir, rel)


def write_rollback_script(rollback_actions, out_path: str):
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write('#!/usr/bin/env bash\n')
        f.write('# Rollback script generated by apply_delete_plan.py\n')
        f.write('set -euo pipefail\n')
        for act in rollback_actions:
            # act: {type: 'restore', backup:..., original:..., symlink:...}
            if act['type'] == 'restore':
                # remove symlink if exists, move backup back
                f.write(f"if [ -L '{act['original']}' ]; then rm '{act['original']}'; fi\n")
                f.write(f"mkdir -p \"$(dirname '{act['original']}')\"\n")
                f.write(f"mv '{act['backup']}' '{act['original']}'\n")
        os.chmod(out_path, 0o750)


def main():
    p = argparse.ArgumentParser()
    p.add_argument('--delete-plan', required=True, help='CSV file produced by detect_duplicates.py')
    p.add_argument('--dry-run', action='store_true', help='Only simulate operations')
    p.add_argument('--apply', action='store_true', help='Apply changes (move + symlink)')
    p.add_argument('--backup-dir', default='scripts/reports/backups', help='Base dir to store backups')
    p.add_argument('--use-hardlink', action='store_true', help='Use hardlink instead of symlink (apply only)')
    args = p.parse_args()

    plan = load_delete_plan(args.delete_plan)
    if not plan:
        print('No rows in delete plan file:', args.delete_plan)
        return 0

    timestamp = datetime.utcnow().strftime('%Y%m%d_%H%M%S')
    base_backup = os.path.abspath(os.path.join(args.backup_dir, timestamp))

    planned_ops = []
    for r in plan:
        sha = r.get('sha256') or r.get('sha') or ''
        keep = r.get('keep_path')
        delete = r.get('delete_path')
        reason = r.get('reason', '')
        if not keep or not delete:
            print('Skipping malformed row:', r)
            continue
        planned_ops.append({'sha': sha, 'keep': keep, 'delete': delete, 'reason': reason})

    # Validate existence and sha
    validations = []
    for op in planned_ops:
        keep_exists = os.path.exists(op['keep'])
        delete_exists = os.path.exists(op['delete'])
        sha_ok = None
        if op['sha'] and delete_exists:
            try:
                found = sha256_of(op['delete'])
                sha_ok = (found.startswith(op['sha']))
            except Exception as e:
                sha_ok = False
        validations.append((op, keep_exists, delete_exists, sha_ok))

    # Print summary
    print('Planned operations:', len(planned_ops))
    cnt_missing_keep = sum(1 for _,k,d,s in validations if not k)
    cnt_missing_delete = sum(1 for _,k,d,s in validations if not d)
    cnt_sha_mismatch = sum(1 for _,k,d,s in validations if (s is False))
    print('Missing keep files:', cnt_missing_keep)
    print('Missing delete files:', cnt_missing_delete)
    print('SHA mismatches (delete file present but sha differs):', cnt_sha_mismatch)

    # Show sample planned ops (first 30)
    print('\nSample planned ops:')
    for i,(op,k,d,s) in enumerate(validations[:200]):
        print(f"{i+1}. keep={'OK' if k else 'MISSING'} delete={'OK' if d else 'MISSING'} sha_ok={s} -> keep={op['keep']} delete={op['delete']}")

    if not args.apply:
        print('\nDry-run complete. To apply these changes run with --apply --backup-dir <dir>')
        return 0

    # Confirm apply mode
    # create backup dir
    os.makedirs(base_backup, exist_ok=True)
    apply_log_path = os.path.join(os.path.dirname(args.delete_plan), 'apply_log.csv')
    rollback_actions = []

    with open(apply_log_path, 'w', newline='', encoding='utf-8') as logf:
        writer = csv.writer(logf)
        writer.writerow(['ts','sha256','keep_path','delete_path','action','backup_path','error'])
        for op,k,d,s in validations:
            ts = datetime.utcnow().isoformat()
            if not k or not d:
                writer.writerow([ts, op['sha'], op['keep'], op['delete'], 'skipped_missing', '','keep_or_delete_missing'])
                continue
            # verify sha if provided
            if op['sha'] and s is False:
                writer.writerow([ts, op['sha'], op['keep'], op['delete'], 'skipped_sha_mismatch', '', 'sha_mismatch'])
                continue

            # move delete file to backup location preserving relative structure
            try:
                backup_path = make_backup_path(base_backup, op['delete'])
                ensure_parent(backup_path)
                # move file
                shutil.move(op['delete'], backup_path)
                # create symlink or hardlink at original location
                ensure_parent(op['delete'])
                if args.use_hardlink:
                    os.link(backup_path, op['delete'])
                    action = 'moved_and_hardlink'
                else:
                    os.symlink(op['keep'], op['delete'])
                    action = 'moved_and_symlink'

                writer.writerow([ts, op['sha'], op['keep'], op['delete'], action, backup_path, ''])
                rollback_actions.append({'type':'restore','backup':backup_path,'original':op['delete']})
            except Exception as e:
                writer.writerow([ts, op['sha'], op['keep'], op['delete'], 'error', '', str(e)])

    rollback_path = os.path.join(os.path.dirname(args.delete_plan), 'apply_rollback.sh')
    write_rollback_script(rollback_actions, rollback_path)
    print('\nApply complete. Logs at', apply_log_path)
    print('Rollback script:', rollback_path)
    print('Backups under', base_backup)
    return 0


if __name__ == '__main__':
    sys.exit(main())
