"""Generate SQL to update avatar_asset rows after resizing assets.

Reads the resize report CSV (generated by backend/scripts/resize_assets.py) and emits:
 - a psql \copy command (printed) to snapshot current rows for the affected filenames
 - an apply SQL file: update width,height,file_size,sha256 for each filename
 - a rollback SQL file: will restore previous values by id after you run the psql copy to capture them

Usage:
    python backend/scripts/generate_resize_db_updates.py --report backend/scripts/reports/reports/resize_report_apply.csv

It writes files into backend/scripts/reports/reports/
"""
from __future__ import annotations
import argparse
import csv
from pathlib import Path
import time

ROOT = Path(__file__).resolve().parents[1]
REPORTS = ROOT / "scripts" / "reports" / "reports"
TS = time.strftime("%Y%m%d_%H%M%S")


def q(s: str) -> str:
    return s.replace("'", "''")


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--report", type=str, default=str(REPORTS / "resize_report_apply.csv"))
    args = p.parse_args()

    report_path = Path(args.report)
    if not report_path.exists():
        print("Report not found:", report_path)
        return 1

    rows = []
    with report_path.open(encoding="utf-8") as fh:
        reader = csv.DictReader(fh)
        for r in reader:
            status = (r.get('status') or '').strip()
            if status in ('resized', 'would_resize'):
                fname = (r.get('filename') or '').strip()
                sha = (r.get('sha256') or '').strip()
                fsize = (r.get('file_size') or '').strip()
                # Normalize fsize to integer if possible
                try:
                    fsize_int = int(fsize) if fsize else None
                except Exception:
                    fsize_int = None
                rows.append({
                    'filename': fname,
                    'sha256': sha,
                    'file_size': fsize_int,
                    'width': 512,
                    'height': 512,
                })

    if not rows:
        print("No resized rows found in report.")
        return 0

    filenames = [r['filename'] for r in rows]
    quoted = ','.join("'{}'".format(q(fn)) for fn in filenames)

    out_apply = REPORTS / f"resize_apply_avatar_asset_{TS}.sql"
    out_rollback = REPORTS / f"resize_apply_avatar_asset_{TS}_rollback.sql"
    snapshot_csv = REPORTS / f"preapply_resize_avatar_asset_snapshot_{TS}.csv"

    # Print psql copy command for snapshot
    copy_cmd = f"\\copy (SELECT id, filename, width, height, file_size, sha256 FROM avatar_asset WHERE filename IN ({quoted})) TO '{snapshot_csv}' CSV HEADER;"

    with out_apply.open('w', encoding='utf-8') as afh:
        afh.write("-- Generated apply SQL to update avatar_asset after resizing assets\n")
        afh.write(f"-- Snapshot command (run in psql) to capture existing rows before applying:\n")
        afh.write(f"-- {copy_cmd}\n\n")
        afh.write("BEGIN;\n\n")
        for r in rows:
            fn = q(r['filename'])
            sha = r['sha256'] or ''
            file_size = r['file_size'] if r['file_size'] is not None else 'NULL'
            afh.write("-- Update for file: {fn}\n".format(fn=fn))
            afh.write("UPDATE avatar_asset SET width = 512, height = 512, file_size = {fs}, sha256 = '{sha}' WHERE filename = '{fn}';\n".format(fs=file_size, sha=q(sha), fn=fn))
            afh.write("\n")
        afh.write("COMMIT;\n")

    # Rollback will be generated from the snapshot by reading CSV (we cannot read it now). So provide template that uses the snapshot.
    with out_rollback.open('w', encoding='utf-8') as rfh:
        rfh.write("-- Rollback SQL generated template. This requires that you run the psql \\copy snapshot first to '{csv}'.\n".format(csv=str(snapshot_csv)))
        rfh.write("-- After running the copy, run the following to revert values (this file assumes the snapshot CSV exists at the path above).\n")
        rfh.write("-- The snapshot contains columns: id,filename,width,height,file_size,sha256\n\n")
        rfh.write("\n-- Example Python snippet to generate rollback from the CSV:\n")
        rfh.write("-- import csv\n")
        rfh.write("-- with open('" + str(snapshot_csv) + "', encoding='utf-8') as fh:\n")
        rfh.write("--     r = csv.DictReader(fh)\n")
        rfh.write("--     for row in r:\n")
        rfh.write("--         print(f\"UPDATE avatar_asset SET width = {row['width']}, height = {row['height']}, file_size = {row['file_size']}, sha256 = '{row['sha256']}' WHERE id = {row['id']};\")\n")

    print("Wrote apply SQL:", out_apply)
    print("Wrote rollback template:", out_rollback)
    print()
    print("Run the following in psql to snapshot current rows BEFORE applying the SQL:")
    print(copy_cmd)
    print()
    print("Then run the apply SQL file in psql:")
    print(f"psql -v ON_ERROR_STOP=1 -f {out_apply}")
    print()
    print("If you need help generating rollback SQL from the snapshot CSV, I can generate it once you run the snapshot and provide the file.")

    return 0


if __name__ == '__main__':
    raise SystemExit(main())
