BEGIN;
UPDATE avatar_asset SET canonical_path = NULL, sha256 = NULL WHERE filename = '/run/media/arch/Storage/SENA/Proyecto-Formativo/Acadify/backend/static/assets/backgrounds/bg_002.png';
UPDATE avatar_asset SET canonical_path = NULL, sha256 = NULL WHERE filename = '/run/media/arch/Storage/SENA/Proyecto-Formativo/Acadify/backend/static/assets/clothes/male/falda_2.png';
UPDATE avatar_asset SET canonical_path = NULL, sha256 = NULL WHERE filename = '/run/media/arch/Storage/SENA/Proyecto-Formativo/Acadify/backend/static/assets/makeup/male/remolino_rubor.png';
UPDATE avatar_asset SET canonical_path = NULL, sha256 = NULL WHERE filename = '/run/media/arch/Storage/SENA/Proyecto-Formativo/Acadify/backend/static/assets/clothes/male/Camisa_morada_mujer.png';
UPDATE avatar_asset SET canonical_path = NULL, sha256 = NULL WHERE filename = '/run/media/arch/Storage/SENA/Proyecto-Formativo/Acadify/backend/static/assets/clothes/female/camisa_cafe_mujer.png';
UPDATE avatar_asset SET canonical_path = NULL, sha256 = NULL WHERE filename = '/run/media/arch/Storage/SENA/Proyecto-Formativo/Acadify/backend/static/assets/clothes/male/Corset_rojo.png';
UPDATE avatar_asset SET canonical_path = NULL, sha256 = NULL WHERE filename = '/run/media/arch/Storage/SENA/Proyecto-Formativo/Acadify/backend/static/assets/base/base-man/167 sin título_20250922233558.png';
UPDATE avatar_asset SET canonical_path = NULL, sha256 = NULL WHERE filename = '/run/media/arch/Storage/SENA/Proyecto-Formativo/Acadify/backend/static/assets/makeup/male/ahumado_negro.png';
UPDATE avatar_asset SET canonical_path = NULL, sha256 = NULL WHERE filename = '/run/media/arch/Storage/SENA/Proyecto-Formativo/Acadify/backend/static/assets/clothes/male/calentadoras.png';
UPDATE avatar_asset SET canonical_path = NULL, sha256 = NULL WHERE filename = '/run/media/arch/Storage/SENA/Proyecto-Formativo/Acadify/backend/static/assets/eyes/male/ojos_5.png';
UPDATE avatar_asset SET canonical_path = NULL, sha256 = NULL WHERE filename = '/run/media/arch/Storage/SENA/Proyecto-Formativo/Acadify/backend/static/assets/hair/male/hair_1.png';
UPDATE avatar_asset SET canonical_path = NULL, sha256 = NULL WHERE filename = '/run/media/arch/Storage/SENA/Proyecto-Formativo/Acadify/backend/static/assets/clothes/male/esqueleto_azul.png';
UPDATE avatar_asset SET canonical_path = NULL, sha256 = NULL WHERE filename = '/run/media/arch/Storage/SENA/Proyecto-Formativo/Acadify/backend/static/assets/clothes/male/Camisa_negra_mujer.png';
UPDATE avatar_asset SET canonical_path = NULL, sha256 = NULL WHERE filename = '/run/media/arch/Storage/SENA/Proyecto-Formativo/Acadify/backend/static/assets/clothes/male/falda_miku.png';
UPDATE avatar_asset SET canonical_path = NULL, sha256 = NULL WHERE filename = '/run/media/arch/Storage/SENA/Proyecto-Formativo/Acadify/backend/static/assets/accessories/male/orejas_gato.png';
UPDATE avatar_asset SET canonical_path = NULL, sha256 = NULL WHERE filename = '/run/media/arch/Storage/SENA/Proyecto-Formativo/Acadify/backend/static/assets/clothes/male/esqueleto_blanco_mujer.png';
UPDATE avatar_asset SET canonical_path = NULL, sha256 = NULL WHERE filename = '/run/media/arch/Storage/SENA/Proyecto-Formativo/Acadify/backend/static/assets/eyes/male/ojos_4.png';
UPDATE avatar_asset SET canonical_path = NULL, sha256 = NULL WHERE filename = '/run/media/arch/Storage/SENA/Proyecto-Formativo/Acadify/backend/static/assets/clothes/male/Camisa_roja_mujer.png';
UPDATE avatar_asset SET canonical_path = NULL, sha256 = NULL WHERE filename = '/run/media/arch/Storage/SENA/Proyecto-Formativo/Acadify/backend/static/assets/clothes/male/camisa_elegante_mujer.png';
UPDATE avatar_asset SET canonical_path = NULL, sha256 = NULL WHERE filename = '/run/media/arch/Storage/SENA/Proyecto-Formativo/Acadify/backend/static/assets/clothes/male/vestido.png';
UPDATE avatar_asset SET canonical_path = NULL, sha256 = NULL WHERE filename = '/run/media/arch/Storage/SENA/Proyecto-Formativo/Acadify/backend/static/assets/clothes/male/Medias_maya.png';
UPDATE avatar_asset SET canonical_path = NULL, sha256 = NULL WHERE filename = '/run/media/arch/Storage/SENA/Proyecto-Formativo/Acadify/backend/static/assets/clothes/male/falda_blanca.png';
UPDATE avatar_asset SET canonical_path = NULL, sha256 = NULL WHERE filename = '/run/media/arch/Storage/SENA/Proyecto-Formativo/Acadify/backend/static/assets/hair/male/hair_3.png';
UPDATE avatar_asset SET canonical_path = NULL, sha256 = NULL WHERE filename = '/run/media/arch/Storage/SENA/Proyecto-Formativo/Acadify/backend/static/assets/hair/male/hair_2.png';
UPDATE avatar_asset SET canonical_path = NULL, sha256 = NULL WHERE filename = '/run/media/arch/Storage/SENA/Proyecto-Formativo/Acadify/backend/static/assets/makeup/male/ahumado_morado.png';
UPDATE avatar_asset SET canonical_path = NULL, sha256 = NULL WHERE filename = '/run/media/arch/Storage/SENA/Proyecto-Formativo/Acadify/backend/static/assets/clothes/male/Camisa_verde_mujer.png';
UPDATE avatar_asset SET canonical_path = NULL, sha256 = NULL WHERE filename = '/run/media/arch/Storage/SENA/Proyecto-Formativo/Acadify/backend/static/assets/accessories/male/manilla_2.png';
UPDATE avatar_asset SET canonical_path = NULL, sha256 = NULL WHERE filename = '/run/media/arch/Storage/SENA/Proyecto-Formativo/Acadify/backend/static/assets/base/base-woman/167 sin título_20250922233650.png';
UPDATE avatar_asset SET canonical_path = NULL, sha256 = NULL WHERE filename = '/run/media/arch/Storage/SENA/Proyecto-Formativo/Acadify/backend/static/assets/accessories/male/manilla_1.png';
UPDATE avatar_asset SET canonical_path = NULL, sha256 = NULL WHERE filename = '/run/media/arch/Storage/SENA/Proyecto-Formativo/Acadify/backend/static/assets/clothes/male/camisa_miku.png';
UPDATE avatar_asset SET canonical_path = NULL, sha256 = NULL WHERE filename = '/run/media/arch/Storage/SENA/Proyecto-Formativo/Acadify/backend/static/assets/base/base-man/167 sin título_20250923002615.png';
UPDATE avatar_asset SET canonical_path = NULL, sha256 = NULL WHERE filename = '/run/media/arch/Storage/SENA/Proyecto-Formativo/Acadify/backend/static/assets/clothes/male/zapatos_beige.png';
UPDATE avatar_asset SET canonical_path = NULL, sha256 = NULL WHERE filename = '/run/media/arch/Storage/SENA/Proyecto-Formativo/Acadify/backend/static/assets/clothes/male/camisa_cafe.png';
UPDATE avatar_asset SET canonical_path = NULL, sha256 = NULL WHERE filename = '/run/media/arch/Storage/SENA/Proyecto-Formativo/Acadify/backend/static/assets/clothes/male/zapatos_rosados.png';
UPDATE avatar_asset SET canonical_path = NULL, sha256 = NULL WHERE filename = '/run/media/arch/Storage/SENA/Proyecto-Formativo/Acadify/backend/static/assets/hair/male/hair_4.png';
UPDATE avatar_asset SET canonical_path = NULL, sha256 = NULL WHERE filename = '/run/media/arch/Storage/SENA/Proyecto-Formativo/Acadify/backend/static/assets/accessories/male/moño.png';
UPDATE avatar_asset SET canonical_path = NULL, sha256 = NULL WHERE filename = '/run/media/arch/Storage/SENA/Proyecto-Formativo/Acadify/backend/static/assets/accessories/male/collar_1.png';
UPDATE avatar_asset SET canonical_path = NULL, sha256 = NULL WHERE filename = '/run/media/arch/Storage/SENA/Proyecto-Formativo/Acadify/backend/static/assets/mouth/male/boca_3.png';
UPDATE avatar_asset SET canonical_path = NULL, sha256 = NULL WHERE filename = '/run/media/arch/Storage/SENA/Proyecto-Formativo/Acadify/backend/static/assets/makeup/male/rubor.png';
UPDATE avatar_asset SET canonical_path = NULL, sha256 = NULL WHERE filename = '/run/media/arch/Storage/SENA/Proyecto-Formativo/Acadify/backend/static/assets/base/base-woman/167 sin título_20250923002534.png';
UPDATE avatar_asset SET canonical_path = NULL, sha256 = NULL WHERE filename = '/run/media/arch/Storage/SENA/Proyecto-Formativo/Acadify/backend/static/assets/accessories/male/gafas_2.png';
UPDATE avatar_asset SET canonical_path = NULL, sha256 = NULL WHERE filename = '/run/media/arch/Storage/SENA/Proyecto-Formativo/Acadify/backend/static/assets/eyes/male/ojos_6.png';
COMMIT;
