from src.crud.academic.crud_institucion import Institucion
from src.crud.academic.crud_programa import Programa
from src.crud.academic.crud_curso import Curso
from src.crud.academic.crud_curso_docente import CursoDocente
from src.crud.academic.crud_grupo import Grupo
from src.crud.academic.crud_grupo_curso import GrupoCurso
from src.crud.academic.crud_estudiante_grupo import EstudianteGrupo
from src.crud.academic.crud_material_educativo import MaterialEducativo
from src.crud.academic.crud_material_clase import MaterialClase
from src.crud.academic.crud_material_curso import MaterialCurso
