"""Add institution states and invitation tokens

Revision ID: 142455def377
Revises: 24f5baaf2c45
Create Date: 2025-09-18 16:06:41.670762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '142455def377'
down_revision: Union[str, Sequence[str], None] = '24f5baaf2c45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('CursoDocente', sa.Column('fecha_asignacion', sa.DATE(), nullable=True))
    op.drop_column('CursoDocente', 'fecha_asignada')
    # Crear el tipo ENUM antes de usarlo
    estado_enum = postgresql.ENUM('pendiente', 'activa', 'suspendida', 'inactiva', name='estado_institucion')
    estado_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('Institucion', sa.Column('estado', estado_enum, server_default=sa.text("'pendiente'"), nullable=False))
    op.add_column('Institucion', sa.Column('fecha_creacion', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('Institucion', sa.Column('fecha_activacion', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.alter_column('Institucion', 'telefono',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=25),
               existing_nullable=False)
    op.create_unique_constraint(None, 'TemaPredefinido', ['tema_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'TemaPredefinido', type_='unique')
    op.alter_column('Institucion', 'telefono',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('Institucion', 'fecha_activacion')
    op.drop_column('Institucion', 'fecha_creacion')
    op.drop_column('Institucion', 'estado')
    estado_enum = postgresql.ENUM('pendiente', 'activa', 'suspendida', 'inactiva', name='estado_institucion')
    estado_enum.drop(op.get_bind(), checkfirst=True)
    op.add_column('CursoDocente', sa.Column('fecha_asignada', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('CursoDocente', 'fecha_asignacion')
    # ### end Alembic commands ###
