"""add_extended_institution_fields_modalidad_calendario_dominios

Revision ID: 8912dfc388c0
Revises: 2b558f86de94
Create Date: 2025-10-30 14:38:56.761980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8912dfc388c0'
down_revision: Union[str, Sequence[str], None] = '2b558f86de94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion_notificaciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('notificaciones_activas', sa.Boolean(), nullable=True),
    sa.Column('sonido_activo', sa.Boolean(), nullable=True),
    sa.Column('tareas_nuevas', sa.Boolean(), nullable=True),
    sa.Column('tareas_vencimiento_24h', sa.Boolean(), nullable=True),
    sa.Column('tareas_vencimiento_1h', sa.Boolean(), nullable=True),
    sa.Column('tareas_calificadas', sa.Boolean(), nullable=True),
    sa.Column('tareas_comentarios', sa.Boolean(), nullable=True),
    sa.Column('mensajes_directos', sa.Boolean(), nullable=True),
    sa.Column('menciones', sa.Boolean(), nullable=True),
    sa.Column('respuestas_hilos', sa.Boolean(), nullable=True),
    sa.Column('mensajes_importantes', sa.Boolean(), nullable=True),
    sa.Column('resumen_diario_email', sa.Boolean(), nullable=True),
    sa.Column('urgentes_email', sa.Boolean(), nullable=True),
    sa.Column('menciones_email', sa.Boolean(), nullable=True),
    sa.Column('horario_inicio', sa.String(length=5), nullable=True),
    sa.Column('horario_fin', sa.String(length=5), nullable=True),
    sa.Column('dias_activos', sa.JSON(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['Usuario.usuario_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('participantes_sala',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sala_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('es_admin', sa.Boolean(), nullable=True),
    sa.Column('es_moderador', sa.Boolean(), nullable=True),
    sa.Column('puede_escribir', sa.Boolean(), nullable=True),
    sa.Column('esta_activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_union', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_ultima_lectura', sa.DateTime(), nullable=True),
    sa.Column('mensajes_no_leidos', sa.Integer(), nullable=True),
    sa.Column('notificaciones_activas', sa.Boolean(), nullable=True),
    sa.Column('sonido_activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['sala_id'], ['salas_chat.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['Usuario.usuario_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lecturas_mensajes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mensaje_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('fecha_lectura', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['mensaje_id'], ['mensajes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['Usuario.usuario_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Mensaje',
    sa.Column('mensaje_id', sa.UUID(), nullable=False),
    sa.Column('chat_grupo_id', sa.UUID(), nullable=False),
    sa.Column('emisor_id', sa.UUID(), nullable=True),
    sa.Column('fecha_hora', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tipo', postgresql.ENUM('texto', 'archivo', 'imagen', 'audio', name='tipo_mensaje'), nullable=False),
    sa.Column('contenido', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['chat_grupo_id'], ['ChatGrupo.chat_grupo_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['emisor_id'], ['Usuario.usuario_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('mensaje_id')
    )
    op.create_table('Tarea',
    sa.Column('tarea_id', sa.UUID(), server_default=sa.text('gen_random_default()'), nullable=False),
    sa.Column('docente_id', sa.UUID(), nullable=True),
    sa.Column('clase_id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.TEXT(), nullable=True),
    sa.Column('fecha_asignacion', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_limite', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('archivo_adjunto', sa.TEXT(), nullable=True),
    sa.Column('permite_entregas_tardias', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['clase_id'], ['Clase.clase_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['docente_id'], ['Docente.docente_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('tarea_id')
    )
    op.create_table('EntregarTarea',
    sa.Column('entrega_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tarea_id', sa.UUID(), nullable=False),
    sa.Column('estudiante_id', sa.UUID(), nullable=False),
    sa.Column('archivo', sa.TEXT(), nullable=False),
    sa.Column('fecha_envio', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('calificacion', sa.NUMERIC(precision=3, scale=1), nullable=True),
    sa.Column('fecha_revision', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint('calificacion >= 0 AND calificacion <= 5', name='chk_calificacion'),
    sa.ForeignKeyConstraint(['estudiante_id'], ['Estudiante.estudiante_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tarea_id'], ['Tarea.tarea_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entrega_id'),
    sa.UniqueConstraint('tarea_id', 'estudiante_id', name='uq_entrega')
    )
    op.drop_index(op.f('idx_reacciones_activo'), table_name='Reacciones')
    op.drop_index(op.f('idx_reacciones_comentario_id'), table_name='Reacciones')
    op.drop_index(op.f('idx_reacciones_comentario_usuario'), table_name='Reacciones')
    op.drop_index(op.f('idx_reacciones_emoji'), table_name='Reacciones')
    op.drop_index(op.f('idx_reacciones_usuario_id'), table_name='Reacciones')
    op.drop_table('Reacciones')
    op.drop_index(op.f('ix_invitation_tokens_codigo'), table_name='invitation_tokens')
    op.drop_index(op.f('ix_invitation_tokens_id'), table_name='invitation_tokens')
    op.drop_table('invitation_tokens')
    op.alter_column('Comentario', 'archivos_adjuntos',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('idx_comentario_activo'), table_name='Comentario')
    op.drop_index(op.f('idx_comentario_autor_fecha'), table_name='Comentario')
    op.drop_index(op.f('idx_comentario_autor_id'), table_name='Comentario')
    op.drop_index(op.f('idx_comentario_curso_fecha'), table_name='Comentario')
    op.drop_index(op.f('idx_comentario_curso_id'), table_name='Comentario')
    op.drop_index(op.f('idx_comentario_fecha_creacion'), table_name='Comentario')
    op.drop_index(op.f('idx_comentario_padre'), table_name='Comentario')
    op.drop_index(op.f('idx_comentario_tipo'), table_name='Comentario')
    op.drop_index(op.f('idx_comentario_tipo_activo'), table_name='Comentario')
    op.drop_index(op.f('idx_comentarios_autor_id'), table_name='Comentario')
    op.drop_index(op.f('idx_comentarios_curso_id'), table_name='Comentario', postgresql_where='(comentario_padre_id IS NULL)')
    op.drop_index(op.f('idx_comentarios_curso_tipo_fecha'), table_name='Comentario', postgresql_where='(comentario_padre_id IS NULL)')
    op.drop_index(op.f('idx_comentarios_fecha_creacion'), table_name='Comentario')
    op.drop_index(op.f('idx_comentarios_padre_id'), table_name='Comentario', postgresql_where='(comentario_padre_id IS NOT NULL)')
    op.create_index(op.f('ix_Comentario_activo'), 'Comentario', ['activo'], unique=False)
    op.create_index(op.f('ix_Comentario_autor_id'), 'Comentario', ['autor_id'], unique=False)
    op.create_index(op.f('ix_Comentario_comentario_id'), 'Comentario', ['comentario_id'], unique=False)
    op.create_index(op.f('ix_Comentario_comentario_padre_id'), 'Comentario', ['comentario_padre_id'], unique=False)
    op.create_index(op.f('ix_Comentario_curso_id'), 'Comentario', ['curso_id'], unique=False)
    op.create_index(op.f('ix_Comentario_esta_eliminado'), 'Comentario', ['esta_eliminado'], unique=False)
    op.create_index(op.f('ix_Comentario_fecha_creacion'), 'Comentario', ['fecha_creacion'], unique=False)
    op.create_index(op.f('ix_Comentario_tipo'), 'Comentario', ['tipo'], unique=False)
    op.alter_column('Curso', 'programa_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('Curso', 'nombre',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('Curso', 'codigo_curso',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Código identificador del curso (ej: MAT101)',
               existing_nullable=True)
    op.alter_column('Curso', 'codigo_acceso',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Código para que estudiantes se unan',
               existing_nullable=True)
    op.alter_column('Curso', 'permite_material_estudiantes',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('Curso', 'requiere_aprobacion_material',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('idx_curso_codigo_acceso'), table_name='Curso')
    op.drop_index(op.f('idx_curso_coordinador_id'), table_name='Curso', postgresql_where='(coordinador_id IS NOT NULL)')
    op.drop_index(op.f('idx_curso_institucion_id'), table_name='Curso')
    op.drop_index(op.f('idx_curso_institucion_programa'), table_name='Curso')
    op.drop_index(op.f('idx_curso_programa_id'), table_name='Curso')
    op.create_index('idx_curso_coordinador', 'Curso', ['coordinador_id'], unique=False)
    op.create_index('idx_curso_fechas', 'Curso', ['fecha_inicio', 'fecha_fin'], unique=False)
    op.create_index('idx_curso_institucion', 'Curso', ['institucion_id'], unique=False)
    op.create_index('idx_curso_programa', 'Curso', ['programa_id'], unique=False)
    op.drop_index(op.f('idx_estudiante_grupo_estudiante_grupo'), table_name='EstudianteGrupo')
    op.drop_index(op.f('idx_estudiante_grupo_estudiante_id'), table_name='EstudianteGrupo')
    op.drop_index(op.f('idx_estudiante_grupo_grupo_id'), table_name='EstudianteGrupo')
    op.alter_column('Grupo', 'programa_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('idx_grupo_curso_curso_id'), table_name='GrupoCurso')
    op.drop_index(op.f('idx_grupo_curso_docente_id'), table_name='GrupoCurso')
    op.add_column('Institucion', sa.Column('logo_url', sa.String(length=500), nullable=False, comment='URL del logo institucional (OBLIGATORIO)'))
    op.add_column('Institucion', sa.Column('color_primario', sa.String(length=7), nullable=True, comment='Color primario en formato hexadecimal #RRGGBB (opcional)'))
    op.add_column('Institucion', sa.Column('color_secundario', sa.String(length=7), nullable=True, comment='Color secundario en formato hexadecimal #RRGGBB (opcional)'))
    op.add_column('Institucion', sa.Column('modalidad_ensenanza', postgresql.ENUM('presencial', 'virtual', 'hibrida', 'dual', name='modalidad_ensenanza'), server_default='presencial', nullable=False, comment='Modalidad: presencial, virtual, híbrida o dual'))
    op.add_column('Institucion', sa.Column('tipo_calendario', postgresql.ENUM('semestral', 'trimestral', 'bimestral', 'cuatrimestral', 'anual', 'modular', name='tipo_calendario'), nullable=True, comment='Tipo de calendario académico (semestral, trimestral, etc.)'))
    op.add_column('Institucion', sa.Column('jornadas', postgresql.ARRAY(sa.String()), nullable=True, comment='Array de jornadas disponibles: ["mañana", "tarde", "noche", "fines_de_semana"]'))
    op.add_column('Institucion', sa.Column('dominio_principal', sa.String(length=100), nullable=True, comment='Dominio principal sin @ (ej: arp.edu.co) - para registro automático'))
    op.add_column('Institucion', sa.Column('dominios_adicionales', postgresql.ARRAY(sa.String()), nullable=True, comment='Dominios secundarios para registro automático (ej: ["alumni.arp.edu.co", "docentes.arp.edu.co"])'))
    op.add_column('Institucion', sa.Column('website', sa.String(length=255), nullable=True, comment='Sitio web oficial de la institución'))
    op.add_column('Institucion', sa.Column('redes_sociales', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='JSON con links a redes sociales: {"facebook": "url", "instagram": "url", "linkedin": "url"}'))
    op.add_column('Institucion', sa.Column('acreditacion_nacional', sa.String(length=150), nullable=True, comment='Entidad acreditadora nacional (ej: MEN Colombia, SEP México)'))
    op.add_column('Institucion', sa.Column('acreditacion_internacional', sa.String(length=150), nullable=True, comment='Certificaciones internacionales (ej: ISO 9001, QS Stars)'))
    op.add_column('Institucion', sa.Column('fecha_acreditacion', postgresql.TIMESTAMP(timezone=True), nullable=True, comment='Fecha de obtención de la acreditación principal'))
    op.add_column('Institucion', sa.Column('capacidad_estudiantes', sa.Integer(), nullable=True, comment='Capacidad máxima de estudiantes'))
    op.add_column('Institucion', sa.Column('numero_estudiantes_actual', sa.Integer(), server_default='0', nullable=True, comment='Número actual de estudiantes matriculados'))
    op.add_column('Institucion', sa.Column('numero_docentes', sa.Integer(), server_default='0', nullable=True, comment='Número actual de docentes activos'))
    op.add_column('Institucion', sa.Column('numero_programas_activos', sa.Integer(), server_default='0', nullable=True, comment='Número de programas académicos activos'))
    op.add_column('Institucion', sa.Column('configuracion_regional', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Configuración regional: {"idioma": "es", "zona_horaria": "America/Bogota", "moneda": "COP", "formato_fecha": "DD/MM/YYYY"}'))
    op.add_column('Institucion', sa.Column('campos_personalizados', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Campos personalizados específicos de la institución (ej: {"codigo_DANE": "123456", "regimen_especial": true})'))
    op.alter_column('Institucion', 'usa_programas',
               existing_type=sa.BOOLEAN(),
               comment='TRUE: Universidad/Instituto con programas. FALSE: Colegio sin programas',
               existing_nullable=False)
    op.alter_column('Institucion', 'correo_institucional',
               existing_type=sa.VARCHAR(length=100),
               comment='Correo principal para contacto y envío de invitaciones',
               existing_nullable=False)
    op.alter_column('Institucion', 'estado',
               existing_type=postgresql.ENUM('pendiente', 'activa', 'suspendida', 'inactiva', name='estado_institucion'),
               comment='Estado del ciclo de vida: pendiente (sin coordinador) → activa (operando) → suspendida/inactiva',
               existing_nullable=False,
               existing_server_default=sa.text("'pendiente'::estado_institucion"))
    op.alter_column('Institucion', 'fecha_creacion',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha de creación de la institución en el sistema',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('Institucion', 'fecha_activacion',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Fecha en que el primer coordinador aceptó la invitación',
               existing_nullable=True)
    op.drop_index(op.f('idx_institucion_dominio'), table_name='Institucion')
    op.drop_column('Institucion', 'dominio')
    op.drop_index(op.f('idx_material_clase_clase_id'), table_name='MaterialClase')
    op.alter_column('MaterialCurso', 'curso_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('idx_material_curso_curso_id'), table_name='MaterialCurso')
    op.add_column('MaterialEducativo', sa.Column('carpeta', postgresql.ENUM('lecturas', 'guias', 'tareas', 'examenes', 'recursos', 'multimedia', 'ejercicios', 'bibliografias', 'otros', name='carpeta_material'), nullable=False))
    op.add_column('MaterialEducativo', sa.Column('estado', postgresql.ENUM('activo', 'archivado', 'borrador', 'revision', name='estado_material'), server_default=sa.text("'activo'"), nullable=False))
    op.add_column('MaterialEducativo', sa.Column('tamano_archivo', sa.BIGINT(), nullable=True))
    op.add_column('MaterialEducativo', sa.Column('hash_archivo', sa.String(length=64), nullable=True))
    op.add_column('MaterialEducativo', sa.Column('version', sa.INTEGER(), nullable=False))
    op.add_column('MaterialEducativo', sa.Column('material_original_id', sa.UUID(), nullable=True))
    op.add_column('MaterialEducativo', sa.Column('es_version_actual', sa.Boolean(), nullable=False))
    op.add_column('MaterialEducativo', sa.Column('autor_id', sa.UUID(), nullable=True))
    op.add_column('MaterialEducativo', sa.Column('tags', sa.String(length=500), nullable=True))
    op.add_column('MaterialEducativo', sa.Column('google_drive_id', sa.String(length=50), nullable=True))
    op.add_column('MaterialEducativo', sa.Column('google_drive_url', sa.String(length=500), nullable=True))
    op.add_column('MaterialEducativo', sa.Column('sincronizado_drive', sa.Boolean(), nullable=True))
    op.add_column('MaterialEducativo', sa.Column('fecha_ultima_sync', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('MaterialEducativo', sa.Column('numero_descargas', sa.INTEGER(), nullable=True))
    op.add_column('MaterialEducativo', sa.Column('fecha_ultimo_acceso', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('MaterialEducativo', sa.Column('fecha_creacion', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('MaterialEducativo', sa.Column('fecha_actualizacion', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.alter_column('MaterialEducativo', 'titulo',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.alter_column('MaterialEducativo', 'url_archivo',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('MaterialEducativo', 'formato_archivo',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.create_index('idx_material_carpeta', 'MaterialEducativo', ['carpeta'], unique=False)
    op.create_index('idx_material_estado', 'MaterialEducativo', ['estado'], unique=False)
    op.create_index('idx_material_fecha', 'MaterialEducativo', ['fecha_creacion'], unique=False)
    op.create_index('idx_material_original', 'MaterialEducativo', ['material_original_id'], unique=False)
    op.create_foreign_key(None, 'MaterialEducativo', 'MaterialEducativo', ['material_original_id'], ['material_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'MaterialEducativo', 'Usuario', ['autor_id'], ['usuario_id'], ondelete='SET NULL')
    op.drop_index(op.f('idx_usuario_estado_cuenta'), table_name='Usuario')
    op.drop_index(op.f('idx_usuario_nombres_busqueda'), table_name='Usuario', postgresql_using='gin')
    op.drop_index(op.f('idx_usuario_rol'), table_name='Usuario')
    op.drop_index(op.f('idx_usuario_rol_estado'), table_name='Usuario')
    op.drop_index(op.f('idx_insignias_usuario_usuario_id'), table_name='UsuarioInsignia')
    op.drop_index(op.f('idx_usuario_puntos_usuario_id'), table_name='UsuarioPuntos')
    op.alter_column('banco_preguntas', 'tipo_pregunta',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('OPCION_MULTIPLE', 'VERDADERO_FALSO', 'ENSAYO', 'RESPUESTA_CORTA', 'COMPLETAR', 'EMPAREJAMIENTO', 'ORDENAMIENTO', name='tipopregunta'),
               existing_nullable=False)
    op.alter_column('banco_preguntas', 'dificultad',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('MUY_FACIL', 'FACIL', 'MEDIO', 'DIFICIL', 'MUY_DIFICIL', name='dificultadpregunta'),
               existing_nullable=True,
               existing_server_default=sa.text("'medio'::character varying"))
    op.alter_column('banco_preguntas', 'institucion_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('banco_preguntas', 'revisado_por',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.create_foreign_key(None, 'banco_preguntas', 'Usuario', ['revisado_por'], ['usuario_id'])
    op.alter_column('configuracion_evaluaciones', 'institucion_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('configuracion_evaluaciones', 'creado_por',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.create_foreign_key(None, 'configuracion_evaluaciones', 'Usuario', ['creado_por'], ['usuario_id'])
    op.alter_column('entregas_tareas', 'estudiante_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('entregas_tareas', 'calificado_por',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_entregas_estado'), table_name='entregas_tareas')
    op.drop_index(op.f('idx_entregas_estudiante_id'), table_name='entregas_tareas')
    op.drop_index(op.f('idx_entregas_tarea_id'), table_name='entregas_tareas')
    op.alter_column('eventos_anti_trampa', 'tipo_evento',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('CAMBIO_PESTANA', 'CAMBIO_APLICACION', 'CLIC_FUERA_VENTANA', 'TIEMPO_INACTIVO', 'PANTALLA_COMPLETA_SALIDA', 'TECLAS_SOSPECHOSAS', 'MULTIPLE_SESION_IP', 'PATRON_RESPUESTA_SOSPECHOSO', 'VELOCIDAD_RESPUESTA_ANOMALA', name='tipoevento'),
               existing_nullable=False)
    op.alter_column('examenes', 'tipo_examen',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('EVALUACION', 'PRUEBA', 'EXAMEN_FINAL', 'QUIZ', 'SIMULACRO', 'DIAGNOSTICO', name='tipoexamen'),
               existing_nullable=False,
               existing_server_default=sa.text("'evaluacion'::character varying"))
    op.alter_column('examenes', 'estado_examen',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('BORRADOR', 'PUBLICADO', 'ACTIVO', 'FINALIZADO', 'ARCHIVADO', name='estadoexamen'),
               existing_nullable=False,
               existing_server_default=sa.text("'borrador'::character varying"))
    op.alter_column('examenes', 'curso_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('examenes', 'grupo_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('examenes', 'creado_por',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.create_foreign_key(None, 'examenes', 'Usuario', ['creado_por'], ['usuario_id'])
    op.alter_column('intentos_examen', 'estudiante_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('intentos_examen', 'estado_intento',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('EN_PROGRESO', 'FINALIZADO', 'TIEMPO_AGOTADO', 'CANCELADO', 'ABANDONADO', name='estadointento'),
               existing_nullable=False,
               existing_server_default=sa.text("'en_progreso'::character varying"))
    op.alter_column('intentos_examen', 'revisado_por',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.create_foreign_key(None, 'intentos_examen', 'Usuario', ['estudiante_id'], ['usuario_id'])
    op.create_foreign_key(None, 'intentos_examen', 'Usuario', ['revisado_por'], ['usuario_id'])
    op.add_column('mensajes', sa.Column('texto', sa.Text(), nullable=True))
    op.add_column('mensajes', sa.Column('datos_adjuntos', sa.JSON(), nullable=True))
    op.add_column('mensajes', sa.Column('fecha_edicion', sa.DateTime(), nullable=True))
    op.add_column('mensajes', sa.Column('editado_por', sa.UUID(), nullable=True))
    op.add_column('mensajes', sa.Column('es_respuesta', sa.Boolean(), nullable=True))
    op.add_column('mensajes', sa.Column('total_respuestas', sa.Integer(), nullable=True))
    op.add_column('mensajes', sa.Column('menciones', sa.JSON(), nullable=True))
    op.add_column('mensajes', sa.Column('programado_para', sa.DateTime(), nullable=True))
    op.alter_column('mensajes', 'tipo_mensaje',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('TEXTO', 'IMAGEN', 'ARCHIVO', 'AUDIO', 'VIDEO', 'ENLACE', 'SISTEMA', 'IA', name='tipomensaje'),
               existing_nullable=True)
    op.alter_column('mensajes', 'estado',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('ENVIADO', 'ENTREGADO', 'LEIDO', 'EDITADO', 'ELIMINADO', name='estadomensaje'),
               existing_nullable=True)
    op.drop_constraint(op.f('mensajes_mensaje_padre_id_fkey'), 'mensajes', type_='foreignkey')
    op.drop_constraint(op.f('mensajes_sala_id_fkey'), 'mensajes', type_='foreignkey')
    op.create_foreign_key(None, 'mensajes', 'mensajes', ['mensaje_padre_id'], ['id'])
    op.create_foreign_key(None, 'mensajes', 'Usuario', ['usuario_id'], ['usuario_id'])
    op.create_foreign_key(None, 'mensajes', 'salas_chat', ['sala_id'], ['id'])
    op.drop_column('mensajes', 'numero_respuestas')
    op.drop_column('mensajes', 'menciones_ia')
    op.drop_column('mensajes', 'fecha_eliminacion')
    op.drop_column('mensajes', 'menciones_todos')
    op.drop_column('mensajes', 'contenido')
    op.drop_column('mensajes', 'archivos_urls')
    op.drop_column('mensajes', 'tiene_respuestas')
    op.drop_column('mensajes', 'metadatos_archivos')
    op.drop_column('mensajes', 'menciones_usuarios')
    op.drop_column('mensajes', 'contenido_html')
    op.drop_column('mensajes', 'fecha_actualizacion')
    op.add_column('notificaciones', sa.Column('tipo', sa.String(length=50), nullable=False))
    op.add_column('notificaciones', sa.Column('referencia_id', sa.UUID(), nullable=True))
    op.add_column('notificaciones', sa.Column('referencia_tipo', sa.String(length=50), nullable=True))
    op.drop_index(op.f('idx_notificaciones_leida'), table_name='notificaciones')
    op.drop_index(op.f('idx_notificaciones_tipo'), table_name='notificaciones', postgresql_where='(tipo_notificacion IS NOT NULL)')
    op.drop_index(op.f('idx_notificaciones_usuario_id'), table_name='notificaciones')
    op.drop_index(op.f('idx_notificaciones_usuario_leida_fecha'), table_name='notificaciones')
    op.drop_constraint(op.f('notificaciones_mensaje_id_fkey'), 'notificaciones', type_='foreignkey')
    op.drop_constraint(op.f('notificaciones_sala_id_fkey'), 'notificaciones', type_='foreignkey')
    op.create_foreign_key(None, 'notificaciones', 'Usuario', ['usuario_id'], ['usuario_id'])
    op.drop_column('notificaciones', 'tipo_notificacion')
    op.drop_column('notificaciones', 'url_accion')
    op.drop_column('notificaciones', 'icono')
    op.drop_column('notificaciones', 'mensaje_id')
    op.drop_column('notificaciones', 'tarea_id')
    op.drop_column('notificaciones', 'curso_id')
    op.drop_column('notificaciones', 'sala_id')
    op.drop_column('notificaciones', 'color')
    op.alter_column('preguntas_examen', 'tipo_pregunta',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('OPCION_MULTIPLE', 'VERDADERO_FALSO', 'ENSAYO', 'RESPUESTA_CORTA', 'COMPLETAR', 'EMPAREJAMIENTO', 'ORDENAMIENTO', name='tipopregunta'),
               existing_nullable=False)
    op.alter_column('preguntas_examen', 'dificultad',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('MUY_FACIL', 'FACIL', 'MEDIO', 'DIFICIL', 'MUY_DIFICIL', name='dificultadpregunta'),
               existing_nullable=True,
               existing_server_default=sa.text("'medio'::character varying"))
    op.create_foreign_key(None, 'rubricas', 'Usuario', ['creado_por'], ['usuario_id'])
    op.add_column('salas_chat', sa.Column('requiere_aprobacion', sa.Boolean(), nullable=True))
    op.add_column('salas_chat', sa.Column('max_participantes', sa.Integer(), nullable=True))
    op.add_column('salas_chat', sa.Column('esta_activa', sa.Boolean(), nullable=True))
    op.add_column('salas_chat', sa.Column('fecha_ultima_actividad', sa.DateTime(), nullable=True))
    op.add_column('salas_chat', sa.Column('total_mensajes', sa.Integer(), nullable=True))
    op.add_column('salas_chat', sa.Column('configuracion', sa.JSON(), nullable=True))
    op.alter_column('salas_chat', 'tipo_sala',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('CURSO', 'GRUPO', 'TAREA', 'PRIVADO', 'GENERAL', name='tiposala'),
               existing_nullable=False)
    op.create_foreign_key(None, 'salas_chat', 'Usuario', ['creador_id'], ['usuario_id'])
    op.drop_column('salas_chat', 'configuracion_json')
    op.drop_column('salas_chat', 'permite_menciones')
    op.drop_column('salas_chat', 'ultimo_mensaje_fecha')
    op.drop_column('salas_chat', 'permite_hilos')
    op.drop_column('salas_chat', 'moderacion_activa')
    op.drop_column('salas_chat', 'tags')
    op.add_column('tareas', sa.Column('categoria', sa.String(length=100), nullable=True))
    op.alter_column('tareas', 'grupo_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('tareas', 'docente_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('tareas', 'tipo_tarea',
               existing_type=postgresql.ENUM('ensayo', 'proyecto', 'ejercicios', 'investigacion', 'presentacion', 'laboratorio', 'lectura', 'examen', 'otro', name='tipo_tarea'),
               type_=sa.Enum('ENSAYO', 'PROYECTO', 'EJERCICIOS', 'INVESTIGACION', 'PRESENTACION', 'LABORATORIO', 'LECTURA', 'EXAMEN', 'OTRO', name='tipotarea'),
               existing_nullable=False,
               existing_server_default=sa.text("'ensayo'::tipo_tarea"))
    op.alter_column('tareas', 'prioridad',
               existing_type=postgresql.ENUM('baja', 'media', 'alta', 'urgente', name='prioridad_tarea'),
               type_=sa.Enum('BAJA', 'MEDIA', 'ALTA', 'URGENTE', name='prioridadtarea'),
               existing_nullable=False,
               existing_server_default=sa.text("'media'::prioridad_tarea"))
    op.alter_column('tareas', 'estado',
               existing_type=postgresql.ENUM('asignada', 'en_progreso', 'entregada', 'calificada', 'vencida', 'cancelada', name='estado_tarea'),
               type_=sa.Enum('ASIGNADA', 'EN_PROGRESO', 'ENTREGADA', 'CALIFICADA', 'VENCIDA', 'CANCELADA', name='estadotarea'),
               existing_nullable=False,
               existing_server_default=sa.text("'asignada'::estado_tarea"))
    op.alter_column('tareas', 'creado_por',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tareas', 'actualizado_por',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_tareas_docente_id'), table_name='tareas')
    op.drop_index(op.f('idx_tareas_estado'), table_name='tareas')
    op.drop_index(op.f('idx_tareas_fecha_limite'), table_name='tareas')
    op.drop_index(op.f('idx_tareas_grupo_id'), table_name='tareas')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_tareas_grupo_id'), 'tareas', ['grupo_id'], unique=False)
    op.create_index(op.f('idx_tareas_fecha_limite'), 'tareas', ['fecha_limite'], unique=False)
    op.create_index(op.f('idx_tareas_estado'), 'tareas', ['estado'], unique=False)
    op.create_index(op.f('idx_tareas_docente_id'), 'tareas', ['docente_id'], unique=False)
    op.alter_column('tareas', 'actualizado_por',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('tareas', 'creado_por',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('tareas', 'estado',
               existing_type=sa.Enum('ASIGNADA', 'EN_PROGRESO', 'ENTREGADA', 'CALIFICADA', 'VENCIDA', 'CANCELADA', name='estadotarea'),
               type_=postgresql.ENUM('asignada', 'en_progreso', 'entregada', 'calificada', 'vencida', 'cancelada', name='estado_tarea'),
               existing_nullable=False,
               existing_server_default=sa.text("'asignada'::estado_tarea"))
    op.alter_column('tareas', 'prioridad',
               existing_type=sa.Enum('BAJA', 'MEDIA', 'ALTA', 'URGENTE', name='prioridadtarea'),
               type_=postgresql.ENUM('baja', 'media', 'alta', 'urgente', name='prioridad_tarea'),
               existing_nullable=False,
               existing_server_default=sa.text("'media'::prioridad_tarea"))
    op.alter_column('tareas', 'tipo_tarea',
               existing_type=sa.Enum('ENSAYO', 'PROYECTO', 'EJERCICIOS', 'INVESTIGACION', 'PRESENTACION', 'LABORATORIO', 'LECTURA', 'EXAMEN', 'OTRO', name='tipotarea'),
               type_=postgresql.ENUM('ensayo', 'proyecto', 'ejercicios', 'investigacion', 'presentacion', 'laboratorio', 'lectura', 'examen', 'otro', name='tipo_tarea'),
               existing_nullable=False,
               existing_server_default=sa.text("'ensayo'::tipo_tarea"))
    op.alter_column('tareas', 'docente_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('tareas', 'grupo_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_column('tareas', 'categoria')
    op.add_column('salas_chat', sa.Column('tags', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('salas_chat', sa.Column('moderacion_activa', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('salas_chat', sa.Column('permite_hilos', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('salas_chat', sa.Column('ultimo_mensaje_fecha', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('salas_chat', sa.Column('permite_menciones', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('salas_chat', sa.Column('configuracion_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'salas_chat', type_='foreignkey')
    op.alter_column('salas_chat', 'tipo_sala',
               existing_type=sa.Enum('CURSO', 'GRUPO', 'TAREA', 'PRIVADO', 'GENERAL', name='tiposala'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('salas_chat', 'configuracion')
    op.drop_column('salas_chat', 'total_mensajes')
    op.drop_column('salas_chat', 'fecha_ultima_actividad')
    op.drop_column('salas_chat', 'esta_activa')
    op.drop_column('salas_chat', 'max_participantes')
    op.drop_column('salas_chat', 'requiere_aprobacion')
    op.drop_constraint(None, 'rubricas', type_='foreignkey')
    op.alter_column('preguntas_examen', 'dificultad',
               existing_type=sa.Enum('MUY_FACIL', 'FACIL', 'MEDIO', 'DIFICIL', 'MUY_DIFICIL', name='dificultadpregunta'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'medio'::character varying"))
    op.alter_column('preguntas_examen', 'tipo_pregunta',
               existing_type=sa.Enum('OPCION_MULTIPLE', 'VERDADERO_FALSO', 'ENSAYO', 'RESPUESTA_CORTA', 'COMPLETAR', 'EMPAREJAMIENTO', 'ORDENAMIENTO', name='tipopregunta'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.add_column('notificaciones', sa.Column('color', sa.VARCHAR(length=7), autoincrement=False, nullable=True))
    op.add_column('notificaciones', sa.Column('sala_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('notificaciones', sa.Column('curso_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('notificaciones', sa.Column('tarea_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('notificaciones', sa.Column('mensaje_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('notificaciones', sa.Column('icono', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('notificaciones', sa.Column('url_accion', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('notificaciones', sa.Column('tipo_notificacion', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'notificaciones', type_='foreignkey')
    op.create_foreign_key(op.f('notificaciones_sala_id_fkey'), 'notificaciones', 'salas_chat', ['sala_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('notificaciones_mensaje_id_fkey'), 'notificaciones', 'mensajes', ['mensaje_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_notificaciones_usuario_leida_fecha'), 'notificaciones', ['usuario_id', 'leida', sa.literal_column('fecha_creacion DESC')], unique=False)
    op.create_index(op.f('idx_notificaciones_usuario_id'), 'notificaciones', ['usuario_id'], unique=False)
    op.create_index(op.f('idx_notificaciones_tipo'), 'notificaciones', ['tipo_notificacion'], unique=False, postgresql_where='(tipo_notificacion IS NOT NULL)')
    op.create_index(op.f('idx_notificaciones_leida'), 'notificaciones', ['leida'], unique=False)
    op.drop_column('notificaciones', 'referencia_tipo')
    op.drop_column('notificaciones', 'referencia_id')
    op.drop_column('notificaciones', 'tipo')
    op.add_column('mensajes', sa.Column('fecha_actualizacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('mensajes', sa.Column('contenido_html', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('mensajes', sa.Column('menciones_usuarios', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('mensajes', sa.Column('metadatos_archivos', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('mensajes', sa.Column('tiene_respuestas', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('mensajes', sa.Column('archivos_urls', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('mensajes', sa.Column('contenido', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('mensajes', sa.Column('menciones_todos', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('mensajes', sa.Column('fecha_eliminacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('mensajes', sa.Column('menciones_ia', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('mensajes', sa.Column('numero_respuestas', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'mensajes', type_='foreignkey')
    op.drop_constraint(None, 'mensajes', type_='foreignkey')
    op.drop_constraint(None, 'mensajes', type_='foreignkey')
    op.create_foreign_key(op.f('mensajes_sala_id_fkey'), 'mensajes', 'salas_chat', ['sala_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('mensajes_mensaje_padre_id_fkey'), 'mensajes', 'mensajes', ['mensaje_padre_id'], ['id'], ondelete='CASCADE')
    op.alter_column('mensajes', 'estado',
               existing_type=sa.Enum('ENVIADO', 'ENTREGADO', 'LEIDO', 'EDITADO', 'ELIMINADO', name='estadomensaje'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('mensajes', 'tipo_mensaje',
               existing_type=sa.Enum('TEXTO', 'IMAGEN', 'ARCHIVO', 'AUDIO', 'VIDEO', 'ENLACE', 'SISTEMA', 'IA', name='tipomensaje'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('mensajes', 'programado_para')
    op.drop_column('mensajes', 'menciones')
    op.drop_column('mensajes', 'total_respuestas')
    op.drop_column('mensajes', 'es_respuesta')
    op.drop_column('mensajes', 'editado_por')
    op.drop_column('mensajes', 'fecha_edicion')
    op.drop_column('mensajes', 'datos_adjuntos')
    op.drop_column('mensajes', 'texto')
    op.drop_constraint(None, 'intentos_examen', type_='foreignkey')
    op.drop_constraint(None, 'intentos_examen', type_='foreignkey')
    op.alter_column('intentos_examen', 'revisado_por',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('intentos_examen', 'estado_intento',
               existing_type=sa.Enum('EN_PROGRESO', 'FINALIZADO', 'TIEMPO_AGOTADO', 'CANCELADO', 'ABANDONADO', name='estadointento'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'en_progreso'::character varying"))
    op.alter_column('intentos_examen', 'estudiante_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_constraint(None, 'examenes', type_='foreignkey')
    op.alter_column('examenes', 'creado_por',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('examenes', 'grupo_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('examenes', 'curso_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('examenes', 'estado_examen',
               existing_type=sa.Enum('BORRADOR', 'PUBLICADO', 'ACTIVO', 'FINALIZADO', 'ARCHIVADO', name='estadoexamen'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'borrador'::character varying"))
    op.alter_column('examenes', 'tipo_examen',
               existing_type=sa.Enum('EVALUACION', 'PRUEBA', 'EXAMEN_FINAL', 'QUIZ', 'SIMULACRO', 'DIAGNOSTICO', name='tipoexamen'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'evaluacion'::character varying"))
    op.alter_column('eventos_anti_trampa', 'tipo_evento',
               existing_type=sa.Enum('CAMBIO_PESTANA', 'CAMBIO_APLICACION', 'CLIC_FUERA_VENTANA', 'TIEMPO_INACTIVO', 'PANTALLA_COMPLETA_SALIDA', 'TECLAS_SOSPECHOSAS', 'MULTIPLE_SESION_IP', 'PATRON_RESPUESTA_SOSPECHOSO', 'VELOCIDAD_RESPUESTA_ANOMALA', name='tipoevento'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.create_index(op.f('idx_entregas_tarea_id'), 'entregas_tareas', ['tarea_id'], unique=False)
    op.create_index(op.f('idx_entregas_estudiante_id'), 'entregas_tareas', ['estudiante_id'], unique=False)
    op.create_index(op.f('idx_entregas_estado'), 'entregas_tareas', ['estado'], unique=False)
    op.alter_column('entregas_tareas', 'calificado_por',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('entregas_tareas', 'estudiante_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_constraint(None, 'configuracion_evaluaciones', type_='foreignkey')
    op.alter_column('configuracion_evaluaciones', 'creado_por',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('configuracion_evaluaciones', 'institucion_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_constraint(None, 'banco_preguntas', type_='foreignkey')
    op.alter_column('banco_preguntas', 'revisado_por',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('banco_preguntas', 'institucion_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('banco_preguntas', 'dificultad',
               existing_type=sa.Enum('MUY_FACIL', 'FACIL', 'MEDIO', 'DIFICIL', 'MUY_DIFICIL', name='dificultadpregunta'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'medio'::character varying"))
    op.alter_column('banco_preguntas', 'tipo_pregunta',
               existing_type=sa.Enum('OPCION_MULTIPLE', 'VERDADERO_FALSO', 'ENSAYO', 'RESPUESTA_CORTA', 'COMPLETAR', 'EMPAREJAMIENTO', 'ORDENAMIENTO', name='tipopregunta'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.create_index(op.f('idx_usuario_puntos_usuario_id'), 'UsuarioPuntos', ['usuario_id'], unique=False)
    op.create_index(op.f('idx_insignias_usuario_usuario_id'), 'UsuarioInsignia', ['usuario_id'], unique=False)
    op.create_index(op.f('idx_usuario_rol_estado'), 'Usuario', ['rol', 'estado_cuenta'], unique=False)
    op.create_index(op.f('idx_usuario_rol'), 'Usuario', ['rol'], unique=False)
    op.create_index(op.f('idx_usuario_nombres_busqueda'), 'Usuario', [sa.literal_column("to_tsvector('spanish'::regconfig, (nombres::text || ' '::text) || apellidos::text)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_usuario_estado_cuenta'), 'Usuario', ['estado_cuenta'], unique=False)
    op.drop_constraint(None, 'MaterialEducativo', type_='foreignkey')
    op.drop_constraint(None, 'MaterialEducativo', type_='foreignkey')
    op.drop_index('idx_material_original', table_name='MaterialEducativo')
    op.drop_index('idx_material_fecha', table_name='MaterialEducativo')
    op.drop_index('idx_material_estado', table_name='MaterialEducativo')
    op.drop_index('idx_material_carpeta', table_name='MaterialEducativo')
    op.alter_column('MaterialEducativo', 'formato_archivo',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('MaterialEducativo', 'url_archivo',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('MaterialEducativo', 'titulo',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('MaterialEducativo', 'fecha_actualizacion')
    op.drop_column('MaterialEducativo', 'fecha_creacion')
    op.drop_column('MaterialEducativo', 'fecha_ultimo_acceso')
    op.drop_column('MaterialEducativo', 'numero_descargas')
    op.drop_column('MaterialEducativo', 'fecha_ultima_sync')
    op.drop_column('MaterialEducativo', 'sincronizado_drive')
    op.drop_column('MaterialEducativo', 'google_drive_url')
    op.drop_column('MaterialEducativo', 'google_drive_id')
    op.drop_column('MaterialEducativo', 'tags')
    op.drop_column('MaterialEducativo', 'autor_id')
    op.drop_column('MaterialEducativo', 'es_version_actual')
    op.drop_column('MaterialEducativo', 'material_original_id')
    op.drop_column('MaterialEducativo', 'version')
    op.drop_column('MaterialEducativo', 'hash_archivo')
    op.drop_column('MaterialEducativo', 'tamano_archivo')
    op.drop_column('MaterialEducativo', 'estado')
    op.drop_column('MaterialEducativo', 'carpeta')
    op.create_index(op.f('idx_material_curso_curso_id'), 'MaterialCurso', ['curso_id'], unique=False)
    op.alter_column('MaterialCurso', 'curso_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('idx_material_clase_clase_id'), 'MaterialClase', ['clase_id'], unique=False)
    op.add_column('Institucion', sa.Column('dominio', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Dominio de correo institucional (ej: arp.edu.co)'))
    op.create_index(op.f('idx_institucion_dominio'), 'Institucion', ['dominio'], unique=False)
    op.alter_column('Institucion', 'fecha_activacion',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Fecha en que el primer coordinador aceptó la invitación',
               existing_nullable=True)
    op.alter_column('Institucion', 'fecha_creacion',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Fecha de creación de la institución en el sistema',
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('Institucion', 'estado',
               existing_type=postgresql.ENUM('pendiente', 'activa', 'suspendida', 'inactiva', name='estado_institucion'),
               comment=None,
               existing_comment='Estado del ciclo de vida: pendiente (sin coordinador) → activa (operando) → suspendida/inactiva',
               existing_nullable=False,
               existing_server_default=sa.text("'pendiente'::estado_institucion"))
    op.alter_column('Institucion', 'correo_institucional',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Correo principal para contacto y envío de invitaciones',
               existing_nullable=False)
    op.alter_column('Institucion', 'usa_programas',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='TRUE: Universidad/Instituto con programas. FALSE: Colegio sin programas',
               existing_nullable=False)
    op.drop_column('Institucion', 'campos_personalizados')
    op.drop_column('Institucion', 'configuracion_regional')
    op.drop_column('Institucion', 'numero_programas_activos')
    op.drop_column('Institucion', 'numero_docentes')
    op.drop_column('Institucion', 'numero_estudiantes_actual')
    op.drop_column('Institucion', 'capacidad_estudiantes')
    op.drop_column('Institucion', 'fecha_acreditacion')
    op.drop_column('Institucion', 'acreditacion_internacional')
    op.drop_column('Institucion', 'acreditacion_nacional')
    op.drop_column('Institucion', 'redes_sociales')
    op.drop_column('Institucion', 'website')
    op.drop_column('Institucion', 'dominios_adicionales')
    op.drop_column('Institucion', 'dominio_principal')
    op.drop_column('Institucion', 'jornadas')
    op.drop_column('Institucion', 'tipo_calendario')
    op.drop_column('Institucion', 'modalidad_ensenanza')
    op.drop_column('Institucion', 'color_secundario')
    op.drop_column('Institucion', 'color_primario')
    op.drop_column('Institucion', 'logo_url')
    op.create_index(op.f('idx_grupo_curso_docente_id'), 'GrupoCurso', ['docente_id'], unique=False)
    op.create_index(op.f('idx_grupo_curso_curso_id'), 'GrupoCurso', ['curso_id'], unique=False)
    op.alter_column('Grupo', 'programa_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('idx_estudiante_grupo_grupo_id'), 'EstudianteGrupo', ['grupo_id'], unique=False)
    op.create_index(op.f('idx_estudiante_grupo_estudiante_id'), 'EstudianteGrupo', ['estudiante_id'], unique=False)
    op.create_index(op.f('idx_estudiante_grupo_estudiante_grupo'), 'EstudianteGrupo', ['estudiante_id', 'grupo_id'], unique=False)
    op.drop_index('idx_curso_programa', table_name='Curso')
    op.drop_index('idx_curso_institucion', table_name='Curso')
    op.drop_index('idx_curso_fechas', table_name='Curso')
    op.drop_index('idx_curso_coordinador', table_name='Curso')
    op.create_index(op.f('idx_curso_programa_id'), 'Curso', ['programa_id'], unique=False)
    op.create_index(op.f('idx_curso_institucion_programa'), 'Curso', ['institucion_id', 'programa_id'], unique=False)
    op.create_index(op.f('idx_curso_institucion_id'), 'Curso', ['institucion_id'], unique=False)
    op.create_index(op.f('idx_curso_coordinador_id'), 'Curso', ['coordinador_id'], unique=False, postgresql_where='(coordinador_id IS NOT NULL)')
    op.create_index(op.f('idx_curso_codigo_acceso'), 'Curso', ['codigo_acceso'], unique=True)
    op.alter_column('Curso', 'requiere_aprobacion_material',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('Curso', 'permite_material_estudiantes',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('Curso', 'codigo_acceso',
               existing_type=sa.VARCHAR(length=10),
               comment='Código para que estudiantes se unan',
               existing_nullable=True)
    op.alter_column('Curso', 'codigo_curso',
               existing_type=sa.VARCHAR(length=20),
               comment='Código identificador del curso (ej: MAT101)',
               existing_nullable=True)
    op.alter_column('Curso', 'nombre',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('Curso', 'programa_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_Comentario_tipo'), table_name='Comentario')
    op.drop_index(op.f('ix_Comentario_fecha_creacion'), table_name='Comentario')
    op.drop_index(op.f('ix_Comentario_esta_eliminado'), table_name='Comentario')
    op.drop_index(op.f('ix_Comentario_curso_id'), table_name='Comentario')
    op.drop_index(op.f('ix_Comentario_comentario_padre_id'), table_name='Comentario')
    op.drop_index(op.f('ix_Comentario_comentario_id'), table_name='Comentario')
    op.drop_index(op.f('ix_Comentario_autor_id'), table_name='Comentario')
    op.drop_index(op.f('ix_Comentario_activo'), table_name='Comentario')
    op.create_index(op.f('idx_comentarios_padre_id'), 'Comentario', ['comentario_padre_id'], unique=False, postgresql_where='(comentario_padre_id IS NOT NULL)')
    op.create_index(op.f('idx_comentarios_fecha_creacion'), 'Comentario', [sa.literal_column('fecha_creacion DESC')], unique=False)
    op.create_index(op.f('idx_comentarios_curso_tipo_fecha'), 'Comentario', ['curso_id', 'tipo', sa.literal_column('fecha_creacion DESC')], unique=False, postgresql_where='(comentario_padre_id IS NULL)')
    op.create_index(op.f('idx_comentarios_curso_id'), 'Comentario', ['curso_id'], unique=False, postgresql_where='(comentario_padre_id IS NULL)')
    op.create_index(op.f('idx_comentarios_autor_id'), 'Comentario', ['autor_id'], unique=False)
    op.create_index(op.f('idx_comentario_tipo_activo'), 'Comentario', ['tipo', 'activo'], unique=False)
    op.create_index(op.f('idx_comentario_tipo'), 'Comentario', ['tipo'], unique=False)
    op.create_index(op.f('idx_comentario_padre'), 'Comentario', ['comentario_padre_id'], unique=False)
    op.create_index(op.f('idx_comentario_fecha_creacion'), 'Comentario', ['fecha_creacion'], unique=False)
    op.create_index(op.f('idx_comentario_curso_id'), 'Comentario', ['curso_id'], unique=False)
    op.create_index(op.f('idx_comentario_curso_fecha'), 'Comentario', ['curso_id', 'fecha_creacion'], unique=False)
    op.create_index(op.f('idx_comentario_autor_id'), 'Comentario', ['autor_id'], unique=False)
    op.create_index(op.f('idx_comentario_autor_fecha'), 'Comentario', ['autor_id', 'fecha_creacion'], unique=False)
    op.create_index(op.f('idx_comentario_activo'), 'Comentario', ['activo'], unique=False)
    op.alter_column('Comentario', 'archivos_adjuntos',
               existing_type=sa.Text(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_table('invitation_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('email_destino', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('institucion_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('estado', postgresql.ENUM('pendiente', 'usado', 'expirado', name='estado_invitacion'), server_default=sa.text("'pendiente'::estado_invitacion"), autoincrement=False, nullable=False),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('fecha_expiracion', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('coordinador_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('usado_en', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['coordinador_id'], ['Usuario.usuario_id'], name=op.f('invitation_tokens_coordinador_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institucion_id'], ['Institucion.institucion_id'], name=op.f('invitation_tokens_institucion_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('invitation_tokens_pkey')),
    sa.UniqueConstraint('codigo', name=op.f('invitation_tokens_codigo_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_invitation_tokens_id'), 'invitation_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_invitation_tokens_codigo'), 'invitation_tokens', ['codigo'], unique=True)
    op.create_table('Reacciones',
    sa.Column('reaccion_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('comentario_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('usuario_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('emoji', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('activo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['comentario_id'], ['Comentario.comentario_id'], name=op.f('Reacciones_comentario_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['Usuario.usuario_id'], name=op.f('Reacciones_usuario_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reaccion_id', name=op.f('Reacciones_pkey')),
    sa.UniqueConstraint('comentario_id', 'usuario_id', 'emoji', name=op.f('uq_user_emoji_per_comment'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_reacciones_usuario_id'), 'Reacciones', ['usuario_id'], unique=False)
    op.create_index(op.f('idx_reacciones_emoji'), 'Reacciones', ['emoji'], unique=False)
    op.create_index(op.f('idx_reacciones_comentario_usuario'), 'Reacciones', ['comentario_id', 'usuario_id'], unique=False)
    op.create_index(op.f('idx_reacciones_comentario_id'), 'Reacciones', ['comentario_id'], unique=False)
    op.create_index(op.f('idx_reacciones_activo'), 'Reacciones', ['activo'], unique=False)
    op.drop_table('EntregarTarea')
    op.drop_table('Tarea')
    op.drop_table('Mensaje')
    op.drop_table('lecturas_mensajes')
    op.drop_table('participantes_sala')
    op.drop_table('configuracion_notificaciones')
    # ### end Alembic commands ###
