"""fix_grupo_periodo_academico_fk_type_integer

Revision ID: 92ce703a9ac9
Revises: 871f0cac36f4
Create Date: 2025-10-30 22:10:40.015281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92ce703a9ac9'
down_revision: Union[str, Sequence[str], None] = '871f0cac36f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion_notificaciones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('notificaciones_activas', sa.Boolean(), nullable=True),
    sa.Column('sonido_activo', sa.Boolean(), nullable=True),
    sa.Column('tareas_nuevas', sa.Boolean(), nullable=True),
    sa.Column('tareas_vencimiento_24h', sa.Boolean(), nullable=True),
    sa.Column('tareas_vencimiento_1h', sa.Boolean(), nullable=True),
    sa.Column('tareas_calificadas', sa.Boolean(), nullable=True),
    sa.Column('tareas_comentarios', sa.Boolean(), nullable=True),
    sa.Column('mensajes_directos', sa.Boolean(), nullable=True),
    sa.Column('menciones', sa.Boolean(), nullable=True),
    sa.Column('respuestas_hilos', sa.Boolean(), nullable=True),
    sa.Column('mensajes_importantes', sa.Boolean(), nullable=True),
    sa.Column('resumen_diario_email', sa.Boolean(), nullable=True),
    sa.Column('urgentes_email', sa.Boolean(), nullable=True),
    sa.Column('menciones_email', sa.Boolean(), nullable=True),
    sa.Column('horario_inicio', sa.String(length=5), nullable=True),
    sa.Column('horario_fin', sa.String(length=5), nullable=True),
    sa.Column('dias_activos', sa.JSON(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['Usuario.usuario_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('participantes_sala',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sala_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('es_admin', sa.Boolean(), nullable=True),
    sa.Column('es_moderador', sa.Boolean(), nullable=True),
    sa.Column('puede_escribir', sa.Boolean(), nullable=True),
    sa.Column('esta_activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_union', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_ultima_lectura', sa.DateTime(), nullable=True),
    sa.Column('mensajes_no_leidos', sa.Integer(), nullable=True),
    sa.Column('notificaciones_activas', sa.Boolean(), nullable=True),
    sa.Column('sonido_activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['sala_id'], ['salas_chat.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['Usuario.usuario_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lecturas_mensajes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mensaje_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('fecha_lectura', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['mensaje_id'], ['mensajes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['Usuario.usuario_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('HistorialAccesoClase',
    sa.Column('historial_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('clase_id', sa.UUID(), nullable=False),
    sa.Column('estudiante_id', sa.UUID(), nullable=False),
    sa.Column('fecha_acceso', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('codigo_usado', sa.String(length=10), nullable=False),
    sa.Column('ip_acceso', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['clase_id'], ['Clase.clase_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['estudiante_id'], ['Estudiante.estudiante_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('historial_id')
    )
    op.create_index('idx_historial_clase_estudiante', 'HistorialAccesoClase', ['clase_id', 'estudiante_id'], unique=False)
    op.create_index('idx_historial_fecha_acceso', 'HistorialAccesoClase', ['fecha_acceso'], unique=False)
    op.create_table('Mensaje',
    sa.Column('mensaje_id', sa.UUID(), nullable=False),
    sa.Column('chat_grupo_id', sa.UUID(), nullable=False),
    sa.Column('emisor_id', sa.UUID(), nullable=True),
    sa.Column('fecha_hora', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tipo', postgresql.ENUM('texto', 'archivo', 'imagen', 'audio', name='tipo_mensaje'), nullable=False),
    sa.Column('contenido', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['chat_grupo_id'], ['ChatGrupo.chat_grupo_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['emisor_id'], ['Usuario.usuario_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('mensaje_id')
    )
    op.create_table('Tarea',
    sa.Column('tarea_id', sa.UUID(), server_default=sa.text('gen_random_default()'), nullable=False),
    sa.Column('docente_id', sa.UUID(), nullable=True),
    sa.Column('clase_id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.TEXT(), nullable=True),
    sa.Column('fecha_asignacion', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_limite', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('archivo_adjunto', sa.TEXT(), nullable=True),
    sa.Column('permite_entregas_tardias', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['clase_id'], ['Clase.clase_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['docente_id'], ['Docente.docente_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('tarea_id')
    )
    op.create_table('EntregarTarea',
    sa.Column('entrega_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tarea_id', sa.UUID(), nullable=False),
    sa.Column('estudiante_id', sa.UUID(), nullable=False),
    sa.Column('archivo', sa.TEXT(), nullable=False),
    sa.Column('fecha_envio', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('calificacion', sa.NUMERIC(precision=3, scale=1), nullable=True),
    sa.Column('fecha_revision', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint('calificacion >= 0 AND calificacion <= 5', name='chk_calificacion'),
    sa.ForeignKeyConstraint(['estudiante_id'], ['Estudiante.estudiante_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tarea_id'], ['Tarea.tarea_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entrega_id'),
    sa.UniqueConstraint('tarea_id', 'estudiante_id', name='uq_entrega')
    )
    op.drop_index(op.f('ix_invitation_tokens_codigo'), table_name='invitation_tokens')
    op.drop_index(op.f('ix_invitation_tokens_id'), table_name='invitation_tokens')
    op.drop_table('invitation_tokens')
    op.drop_index(op.f('idx_reacciones_activo'), table_name='Reacciones')
    op.drop_index(op.f('idx_reacciones_comentario_id'), table_name='Reacciones')
    op.drop_index(op.f('idx_reacciones_comentario_usuario'), table_name='Reacciones')
    op.drop_index(op.f('idx_reacciones_emoji'), table_name='Reacciones')
    op.drop_index(op.f('idx_reacciones_usuario_id'), table_name='Reacciones')
    op.drop_table('Reacciones')
    op.add_column('Clase', sa.Column('grupo_id', sa.UUID(), nullable=False))
    op.add_column('Clase', sa.Column('docente_id', sa.UUID(), nullable=False))
    op.add_column('Clase', sa.Column('tipo_clase', postgresql.ENUM('teorica', 'practica', 'laboratorio', 'taller', 'seminario', 'conferencia', 'examen', 'otro', name='tipo_clase'), nullable=False))
    op.add_column('Clase', sa.Column('estado', postgresql.ENUM('programada', 'en_progreso', 'finalizada', 'cancelada', name='estado_clase'), server_default=sa.text("'programada'"), nullable=False))
    op.add_column('Clase', sa.Column('fecha_inicio', postgresql.TIMESTAMP(timezone=True), nullable=False))
    op.add_column('Clase', sa.Column('fecha_fin', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('Clase', sa.Column('duracion_estimada', sa.INTEGER(), nullable=True))
    op.add_column('Clase', sa.Column('codigo_acceso', sa.String(length=10), nullable=False))
    op.add_column('Clase', sa.Column('estado_codigo', postgresql.ENUM('activo', 'vencido', 'deshabilitado', name='estado_codigo_acceso'), server_default=sa.text("'activo'"), nullable=False))
    op.add_column('Clase', sa.Column('fecha_vencimiento_codigo', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('Clase', sa.Column('max_estudiantes', sa.INTEGER(), nullable=True))
    op.add_column('Clase', sa.Column('fecha_creacion', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('Clase', sa.Column('fecha_actualizacion', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.alter_column('Clase', 'titulo',
               existing_type=sa.TEXT(),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.create_index('idx_clase_codigo_acceso', 'Clase', ['codigo_acceso'], unique=False)
    op.create_index('idx_clase_docente_grupo', 'Clase', ['docente_id', 'grupo_id'], unique=False)
    op.create_index('idx_clase_fecha', 'Clase', ['fecha_inicio'], unique=False)
    op.create_unique_constraint(None, 'Clase', ['codigo_acceso'])
    op.drop_constraint(op.f('Clase_grupo_curso_id_fkey'), 'Clase', type_='foreignkey')
    op.drop_constraint(op.f('Clase_plataforma_id_fkey'), 'Clase', type_='foreignkey')
    op.create_foreign_key(None, 'Clase', 'Docente', ['docente_id'], ['docente_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'Clase', 'Grupo', ['grupo_id'], ['grupo_id'], ondelete='CASCADE')
    op.drop_column('Clase', 'duracion')
    op.drop_column('Clase', 'plataforma_id')
    op.drop_column('Clase', 'link_videollamada')
    op.drop_column('Clase', 'hora_inicio')
    op.drop_column('Clase', 'grupo_curso_id')
    op.alter_column('Comentario', 'archivos_adjuntos',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('idx_comentario_activo'), table_name='Comentario')
    op.drop_index(op.f('idx_comentario_autor_fecha'), table_name='Comentario')
    op.drop_index(op.f('idx_comentario_autor_id'), table_name='Comentario')
    op.drop_index(op.f('idx_comentario_curso_fecha'), table_name='Comentario')
    op.drop_index(op.f('idx_comentario_curso_id'), table_name='Comentario')
    op.drop_index(op.f('idx_comentario_fecha_creacion'), table_name='Comentario')
    op.drop_index(op.f('idx_comentario_padre'), table_name='Comentario')
    op.drop_index(op.f('idx_comentario_tipo'), table_name='Comentario')
    op.drop_index(op.f('idx_comentario_tipo_activo'), table_name='Comentario')
    op.drop_index(op.f('idx_comentarios_autor_id'), table_name='Comentario')
    op.drop_index(op.f('idx_comentarios_curso_id'), table_name='Comentario', postgresql_where='(comentario_padre_id IS NULL)')
    op.drop_index(op.f('idx_comentarios_curso_tipo_fecha'), table_name='Comentario', postgresql_where='(comentario_padre_id IS NULL)')
    op.drop_index(op.f('idx_comentarios_fecha_creacion'), table_name='Comentario')
    op.drop_index(op.f('idx_comentarios_padre_id'), table_name='Comentario', postgresql_where='(comentario_padre_id IS NOT NULL)')
    op.create_index(op.f('ix_Comentario_activo'), 'Comentario', ['activo'], unique=False)
    op.create_index(op.f('ix_Comentario_autor_id'), 'Comentario', ['autor_id'], unique=False)
    op.create_index(op.f('ix_Comentario_comentario_id'), 'Comentario', ['comentario_id'], unique=False)
    op.create_index(op.f('ix_Comentario_comentario_padre_id'), 'Comentario', ['comentario_padre_id'], unique=False)
    op.create_index(op.f('ix_Comentario_curso_id'), 'Comentario', ['curso_id'], unique=False)
    op.create_index(op.f('ix_Comentario_esta_eliminado'), 'Comentario', ['esta_eliminado'], unique=False)
    op.create_index(op.f('ix_Comentario_fecha_creacion'), 'Comentario', ['fecha_creacion'], unique=False)
    op.create_index(op.f('ix_Comentario_tipo'), 'Comentario', ['tipo'], unique=False)
    op.alter_column('Curso', 'programa_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('Curso', 'nombre',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('Curso', 'codigo_curso',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Código identificador del curso (ej: MAT101)',
               existing_nullable=True)
    op.alter_column('Curso', 'codigo_acceso',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Código para que estudiantes se unan',
               existing_nullable=True)
    op.alter_column('Curso', 'permite_material_estudiantes',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('Curso', 'requiere_aprobacion_material',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('idx_curso_categoria'), table_name='Curso')
    op.drop_index(op.f('idx_curso_codigo_acceso'), table_name='Curso')
    op.drop_index(op.f('idx_curso_coordinador_id'), table_name='Curso', postgresql_where='(coordinador_id IS NOT NULL)')
    op.drop_index(op.f('idx_curso_estado'), table_name='Curso')
    op.drop_index(op.f('idx_curso_institucion_id'), table_name='Curso')
    op.drop_index(op.f('idx_curso_institucion_programa'), table_name='Curso')
    op.drop_index(op.f('idx_curso_nivel_dificultad'), table_name='Curso')
    op.drop_index(op.f('idx_curso_programa_id'), table_name='Curso')
    op.drop_index(op.f('idx_curso_tipo'), table_name='Curso')
    op.create_index('idx_curso_coordinador', 'Curso', ['coordinador_id'], unique=False)
    op.create_index('idx_curso_fechas', 'Curso', ['fecha_inicio', 'fecha_fin'], unique=False)
    op.create_index('idx_curso_institucion', 'Curso', ['institucion_id'], unique=False)
    op.create_index('idx_curso_programa', 'Curso', ['programa_id'], unique=False)
    op.drop_index(op.f('idx_estudiante_grupo_estudiante_grupo'), table_name='EstudianteGrupo')
    op.drop_index(op.f('idx_estudiante_grupo_estudiante_id'), table_name='EstudianteGrupo')
    op.drop_index(op.f('idx_estudiante_grupo_grupo_id'), table_name='EstudianteGrupo')
    op.alter_column('Grupo', 'programa_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('Grupo', 'nombre',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.drop_constraint(op.f('Grupo_docente_tutor_id_key'), 'Grupo', type_='unique')
    op.drop_index(op.f('idx_grupo_periodo'), table_name='Grupo')
    op.drop_index(op.f('idx_grupo_tipo'), table_name='Grupo')
    op.create_index(op.f('ix_Grupo_periodo_academico_id'), 'Grupo', ['periodo_academico_id'], unique=False)
    op.drop_index(op.f('idx_grupo_curso_curso_id'), table_name='GrupoCurso')
    op.drop_index(op.f('idx_grupo_curso_docente_id'), table_name='GrupoCurso')
    op.alter_column('Institucion', 'color_primario',
               existing_type=sa.VARCHAR(length=7),
               comment='Color primario en formato hexadecimal #RRGGBB (opcional)',
               existing_comment='Color primario en formato hexadecimal #RRGGBB',
               existing_nullable=True)
    op.alter_column('Institucion', 'color_secundario',
               existing_type=sa.VARCHAR(length=7),
               comment='Color secundario en formato hexadecimal #RRGGBB (opcional)',
               existing_comment='Color secundario en formato hexadecimal #RRGGBB',
               existing_nullable=True)
    op.alter_column('Institucion', 'tipo_calendario',
               existing_type=postgresql.ENUM('semestral', 'trimestral', 'bimestral', 'cuatrimestral', 'anual', 'modular', name='tipo_calendario'),
               comment='Tipo de calendario académico (semestral, trimestral, etc.)',
               existing_comment='Tipo de calendario académico',
               existing_nullable=True)
    op.alter_column('Institucion', 'jornadas',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               comment='Array de jornadas disponibles: ["mañana", "tarde", "noche", "fines_de_semana"]',
               existing_comment='Array de jornadas disponibles',
               existing_nullable=True)
    op.alter_column('Institucion', 'dominios_adicionales',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               comment='Dominios secundarios para registro automático (ej: ["alumni.arp.edu.co", "docentes.arp.edu.co"])',
               existing_comment='Dominios secundarios para registro automático',
               existing_nullable=True)
    op.alter_column('Institucion', 'redes_sociales',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='JSON con links a redes sociales: {"facebook": "url", "instagram": "url", "linkedin": "url"}',
               existing_comment='JSON con links a redes sociales',
               existing_nullable=True)
    op.alter_column('Institucion', 'acreditacion_nacional',
               existing_type=sa.VARCHAR(length=150),
               comment='Entidad acreditadora nacional (ej: MEN Colombia, SEP México)',
               existing_comment='Entidad acreditadora nacional',
               existing_nullable=True)
    op.alter_column('Institucion', 'acreditacion_internacional',
               existing_type=sa.VARCHAR(length=150),
               comment='Certificaciones internacionales (ej: ISO 9001, QS Stars)',
               existing_comment='Certificaciones internacionales',
               existing_nullable=True)
    op.alter_column('Institucion', 'configuracion_regional',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Configuración regional: {"idioma": "es", "zona_horaria": "America/Bogota", "moneda": "COP", "formato_fecha": "DD/MM/YYYY"}',
               existing_comment='Configuración regional',
               existing_nullable=True)
    op.alter_column('Institucion', 'campos_personalizados',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Campos personalizados específicos de la institución (ej: {"codigo_DANE": "123456", "regimen_especial": true})',
               existing_comment='Campos personalizados específicos',
               existing_nullable=True)
    op.alter_column('Institucion', 'estado',
               existing_type=postgresql.ENUM('pendiente', 'activa', 'suspendida', 'inactiva', name='estado_institucion'),
               comment='Estado del ciclo de vida: pendiente (sin coordinador) → activa (operando) → suspendida/inactiva',
               existing_comment='Estado del ciclo de vida: pendiente → activa → suspendida/inactiva',
               existing_nullable=False,
               existing_server_default=sa.text("'pendiente'::estado_institucion"))
    op.drop_index(op.f('idx_material_clase_clase_id'), table_name='MaterialClase')
    op.alter_column('MaterialCurso', 'curso_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('idx_material_curso_curso_id'), table_name='MaterialCurso')
    op.add_column('MaterialEducativo', sa.Column('carpeta', postgresql.ENUM('lecturas', 'guias', 'tareas', 'examenes', 'recursos', 'multimedia', 'ejercicios', 'bibliografias', 'otros', name='carpeta_material'), nullable=False))
    op.add_column('MaterialEducativo', sa.Column('estado', postgresql.ENUM('activo', 'archivado', 'borrador', 'revision', name='estado_material'), server_default=sa.text("'activo'"), nullable=False))
    op.add_column('MaterialEducativo', sa.Column('tamano_archivo', sa.BIGINT(), nullable=True))
    op.add_column('MaterialEducativo', sa.Column('hash_archivo', sa.String(length=64), nullable=True))
    op.add_column('MaterialEducativo', sa.Column('version', sa.INTEGER(), nullable=False))
    op.add_column('MaterialEducativo', sa.Column('material_original_id', sa.UUID(), nullable=True))
    op.add_column('MaterialEducativo', sa.Column('es_version_actual', sa.Boolean(), nullable=False))
    op.add_column('MaterialEducativo', sa.Column('autor_id', sa.UUID(), nullable=True))
    op.add_column('MaterialEducativo', sa.Column('tags', sa.String(length=500), nullable=True))
    op.add_column('MaterialEducativo', sa.Column('google_drive_id', sa.String(length=50), nullable=True))
    op.add_column('MaterialEducativo', sa.Column('google_drive_url', sa.String(length=500), nullable=True))
    op.add_column('MaterialEducativo', sa.Column('sincronizado_drive', sa.Boolean(), nullable=True))
    op.add_column('MaterialEducativo', sa.Column('fecha_ultima_sync', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('MaterialEducativo', sa.Column('numero_descargas', sa.INTEGER(), nullable=True))
    op.add_column('MaterialEducativo', sa.Column('fecha_ultimo_acceso', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.add_column('MaterialEducativo', sa.Column('fecha_creacion', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('MaterialEducativo', sa.Column('fecha_actualizacion', postgresql.TIMESTAMP(timezone=True), nullable=True))
    op.alter_column('MaterialEducativo', 'titulo',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
    op.alter_column('MaterialEducativo', 'url_archivo',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('MaterialEducativo', 'formato_archivo',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.create_index('idx_material_carpeta', 'MaterialEducativo', ['carpeta'], unique=False)
    op.create_index('idx_material_estado', 'MaterialEducativo', ['estado'], unique=False)
    op.create_index('idx_material_fecha', 'MaterialEducativo', ['fecha_creacion'], unique=False)
    op.create_index('idx_material_original', 'MaterialEducativo', ['material_original_id'], unique=False)
    op.create_foreign_key(None, 'MaterialEducativo', 'Usuario', ['autor_id'], ['usuario_id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'MaterialEducativo', 'MaterialEducativo', ['material_original_id'], ['material_id'], ondelete='SET NULL')
    op.alter_column('Programa', 'nombre',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.drop_index(op.f('idx_programa_codigo'), table_name='Programa')
    op.drop_index(op.f('idx_programa_coordinador'), table_name='Programa')
    op.create_index('idx_programa_institucion', 'Programa', ['institucion_id'], unique=False)
    op.create_unique_constraint('uq_programa_codigo', 'Programa', ['institucion_id', 'codigo'])
    op.drop_index(op.f('idx_usuario_estado_cuenta'), table_name='Usuario')
    op.drop_index(op.f('idx_usuario_nombres_busqueda'), table_name='Usuario', postgresql_using='gin')
    op.drop_index(op.f('idx_usuario_rol'), table_name='Usuario')
    op.drop_index(op.f('idx_usuario_rol_estado'), table_name='Usuario')
    op.drop_index(op.f('idx_insignias_usuario_usuario_id'), table_name='UsuarioInsignia')
    op.drop_index(op.f('idx_usuario_puntos_usuario_id'), table_name='UsuarioPuntos')
    op.alter_column('banco_preguntas', 'tipo_pregunta',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('OPCION_MULTIPLE', 'VERDADERO_FALSO', 'ENSAYO', 'RESPUESTA_CORTA', 'COMPLETAR', 'EMPAREJAMIENTO', 'ORDENAMIENTO', name='tipopregunta'),
               existing_nullable=False)
    op.alter_column('banco_preguntas', 'dificultad',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('MUY_FACIL', 'FACIL', 'MEDIO', 'DIFICIL', 'MUY_DIFICIL', name='dificultadpregunta'),
               existing_nullable=True,
               existing_server_default=sa.text("'medio'::character varying"))
    op.alter_column('banco_preguntas', 'institucion_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('banco_preguntas', 'revisado_por',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.create_foreign_key(None, 'banco_preguntas', 'Usuario', ['revisado_por'], ['usuario_id'])
    op.alter_column('configuracion_evaluaciones', 'institucion_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('configuracion_evaluaciones', 'creado_por',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.create_foreign_key(None, 'configuracion_evaluaciones', 'Usuario', ['creado_por'], ['usuario_id'])
    op.alter_column('entregas_tareas', 'estudiante_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('entregas_tareas', 'calificado_por',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_entregas_estado'), table_name='entregas_tareas')
    op.drop_index(op.f('idx_entregas_estudiante_id'), table_name='entregas_tareas')
    op.drop_index(op.f('idx_entregas_tarea_id'), table_name='entregas_tareas')
    op.alter_column('eventos_anti_trampa', 'tipo_evento',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('CAMBIO_PESTANA', 'CAMBIO_APLICACION', 'CLIC_FUERA_VENTANA', 'TIEMPO_INACTIVO', 'PANTALLA_COMPLETA_SALIDA', 'TECLAS_SOSPECHOSAS', 'MULTIPLE_SESION_IP', 'PATRON_RESPUESTA_SOSPECHOSO', 'VELOCIDAD_RESPUESTA_ANOMALA', name='tipoevento'),
               existing_nullable=False)
    op.alter_column('examenes', 'tipo_examen',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('EVALUACION', 'PRUEBA', 'EXAMEN_FINAL', 'QUIZ', 'SIMULACRO', 'DIAGNOSTICO', name='tipoexamen'),
               existing_nullable=False,
               existing_server_default=sa.text("'evaluacion'::character varying"))
    op.alter_column('examenes', 'estado_examen',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('BORRADOR', 'PUBLICADO', 'ACTIVO', 'FINALIZADO', 'ARCHIVADO', name='estadoexamen'),
               existing_nullable=False,
               existing_server_default=sa.text("'borrador'::character varying"))
    op.alter_column('examenes', 'curso_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('examenes', 'grupo_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('examenes', 'creado_por',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.create_foreign_key(None, 'examenes', 'Usuario', ['creado_por'], ['usuario_id'])
    op.add_column('inscripciones', sa.Column('fecha_pre_inscripcion', sa.DateTime(), nullable=True))
    op.alter_column('inscripciones', 'periodo_academico_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('inscripciones', 'fecha_solicitud',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('inscripciones', 'fecha_inicio_clases',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('inscripciones', 'fecha_limite_pago',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('inscripciones', 'fecha_limite_documentos',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('inscripciones', 'fecha_limite_confirmacion',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    op.alter_column('inscripciones', 'costo_total',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('inscripciones', 'costo_matricula',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('inscripciones', 'costo_curso',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('inscripciones', 'otros_costos',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('inscripciones', 'descuentos',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('inscripciones', 'monto_final',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
    op.alter_column('inscripciones', 'calificacion_final',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('inscripciones', 'motivo_atencion',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_inscripciones_en_lista_espera'), table_name='inscripciones')
    op.drop_index(op.f('ix_inscripciones_esta_aprobada'), table_name='inscripciones')
    op.drop_index(op.f('ix_inscripciones_esta_pagado'), table_name='inscripciones')
    op.drop_index(op.f('ix_inscripciones_estudiante_activo'), table_name='inscripciones')
    op.drop_index(op.f('ix_inscripciones_estudiante_grupo'), table_name='inscripciones')
    op.drop_index(op.f('ix_inscripciones_fecha_creacion'), table_name='inscripciones')
    op.drop_index(op.f('ix_inscripciones_grupo_activas'), table_name='inscripciones')
    op.drop_index(op.f('ix_inscripciones_grupo_estado'), table_name='inscripciones')
    op.drop_index(op.f('ix_inscripciones_lista_espera'), table_name='inscripciones')
    op.drop_index(op.f('ix_inscripciones_periodo_estado'), table_name='inscripciones')
    op.drop_index(op.f('ix_inscripciones_tipo_inscripcion'), table_name='inscripciones')
    op.drop_constraint(op.f('uq_inscripcion_codigo'), 'inscripciones', type_='unique')
    op.drop_index(op.f('ix_inscripciones_codigo_inscripcion'), table_name='inscripciones')
    op.create_index(op.f('ix_inscripciones_codigo_inscripcion'), 'inscripciones', ['codigo_inscripcion'], unique=True)
    op.drop_constraint(op.f('inscripciones_periodo_academico_id_fkey'), 'inscripciones', type_='foreignkey')
    op.drop_constraint(op.f('inscripciones_creado_por_id_fkey'), 'inscripciones', type_='foreignkey')
    op.drop_constraint(op.f('inscripciones_estudiante_id_fkey'), 'inscripciones', type_='foreignkey')
    op.drop_constraint(op.f('inscripciones_modificado_por_id_fkey'), 'inscripciones', type_='foreignkey')
    op.drop_constraint(op.f('inscripciones_grupo_id_fkey'), 'inscripciones', type_='foreignkey')
    op.drop_constraint(op.f('inscripciones_aprobada_por_id_fkey'), 'inscripciones', type_='foreignkey')
    op.drop_constraint(op.f('inscripciones_programa_id_fkey'), 'inscripciones', type_='foreignkey')
    op.drop_constraint(op.f('inscripciones_rechazada_por_id_fkey'), 'inscripciones', type_='foreignkey')
    op.create_foreign_key(None, 'inscripciones', 'Usuario', ['creado_por_id'], ['usuario_id'])
    op.create_foreign_key(None, 'inscripciones', 'Usuario', ['rechazada_por_id'], ['usuario_id'])
    op.create_foreign_key(None, 'inscripciones', 'Usuario', ['modificado_por_id'], ['usuario_id'])
    op.create_foreign_key(None, 'inscripciones', 'Usuario', ['estudiante_id'], ['usuario_id'])
    op.create_foreign_key(None, 'inscripciones', 'Programa', ['programa_id'], ['programa_id'])
    op.create_foreign_key(None, 'inscripciones', 'Grupo', ['grupo_id'], ['grupo_id'])
    op.create_foreign_key(None, 'inscripciones', 'periodos_academicos', ['periodo_academico_id'], ['id'])
    op.create_foreign_key(None, 'inscripciones', 'Usuario', ['aprobada_por_id'], ['usuario_id'])
    op.drop_column('inscripciones', 'fecha_preinscripcion')
    op.alter_column('intentos_examen', 'estudiante_id',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('intentos_examen', 'estado_intento',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('EN_PROGRESO', 'FINALIZADO', 'TIEMPO_AGOTADO', 'CANCELADO', 'ABANDONADO', name='estadointento'),
               existing_nullable=False,
               existing_server_default=sa.text("'en_progreso'::character varying"))
    op.alter_column('intentos_examen', 'revisado_por',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.create_foreign_key(None, 'intentos_examen', 'Usuario', ['estudiante_id'], ['usuario_id'])
    op.create_foreign_key(None, 'intentos_examen', 'Usuario', ['revisado_por'], ['usuario_id'])
    op.add_column('mensajes', sa.Column('texto', sa.Text(), nullable=True))
    op.add_column('mensajes', sa.Column('datos_adjuntos', sa.JSON(), nullable=True))
    op.add_column('mensajes', sa.Column('fecha_edicion', sa.DateTime(), nullable=True))
    op.add_column('mensajes', sa.Column('editado_por', sa.UUID(), nullable=True))
    op.add_column('mensajes', sa.Column('es_respuesta', sa.Boolean(), nullable=True))
    op.add_column('mensajes', sa.Column('total_respuestas', sa.Integer(), nullable=True))
    op.add_column('mensajes', sa.Column('menciones', sa.JSON(), nullable=True))
    op.add_column('mensajes', sa.Column('programado_para', sa.DateTime(), nullable=True))
    op.alter_column('mensajes', 'tipo_mensaje',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('TEXTO', 'IMAGEN', 'ARCHIVO', 'AUDIO', 'VIDEO', 'ENLACE', 'SISTEMA', 'IA', name='tipomensaje'),
               existing_nullable=True)
    op.alter_column('mensajes', 'estado',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('ENVIADO', 'ENTREGADO', 'LEIDO', 'EDITADO', 'ELIMINADO', name='estadomensaje'),
               existing_nullable=True)
    op.drop_constraint(op.f('mensajes_mensaje_padre_id_fkey'), 'mensajes', type_='foreignkey')
    op.drop_constraint(op.f('mensajes_sala_id_fkey'), 'mensajes', type_='foreignkey')
    op.create_foreign_key(None, 'mensajes', 'Usuario', ['usuario_id'], ['usuario_id'])
    op.create_foreign_key(None, 'mensajes', 'mensajes', ['mensaje_padre_id'], ['id'])
    op.create_foreign_key(None, 'mensajes', 'salas_chat', ['sala_id'], ['id'])
    op.drop_column('mensajes', 'tiene_respuestas')
    op.drop_column('mensajes', 'contenido_html')
    op.drop_column('mensajes', 'fecha_eliminacion')
    op.drop_column('mensajes', 'menciones_todos')
    op.drop_column('mensajes', 'archivos_urls')
    op.drop_column('mensajes', 'menciones_usuarios')
    op.drop_column('mensajes', 'fecha_actualizacion')
    op.drop_column('mensajes', 'menciones_ia')
    op.drop_column('mensajes', 'contenido')
    op.drop_column('mensajes', 'numero_respuestas')
    op.drop_column('mensajes', 'metadatos_archivos')
    op.add_column('notificaciones', sa.Column('tipo', sa.String(length=50), nullable=False))
    op.add_column('notificaciones', sa.Column('referencia_id', sa.UUID(), nullable=True))
    op.add_column('notificaciones', sa.Column('referencia_tipo', sa.String(length=50), nullable=True))
    op.drop_index(op.f('idx_notificaciones_leida'), table_name='notificaciones')
    op.drop_index(op.f('idx_notificaciones_tipo'), table_name='notificaciones', postgresql_where='(tipo_notificacion IS NOT NULL)')
    op.drop_index(op.f('idx_notificaciones_usuario_id'), table_name='notificaciones')
    op.drop_index(op.f('idx_notificaciones_usuario_leida_fecha'), table_name='notificaciones')
    op.drop_constraint(op.f('notificaciones_mensaje_id_fkey'), 'notificaciones', type_='foreignkey')
    op.drop_constraint(op.f('notificaciones_sala_id_fkey'), 'notificaciones', type_='foreignkey')
    op.create_foreign_key(None, 'notificaciones', 'Usuario', ['usuario_id'], ['usuario_id'])
    op.drop_column('notificaciones', 'sala_id')
    op.drop_column('notificaciones', 'tipo_notificacion')
    op.drop_column('notificaciones', 'tarea_id')
    op.drop_column('notificaciones', 'curso_id')
    op.drop_column('notificaciones', 'url_accion')
    op.drop_column('notificaciones', 'color')
    op.drop_column('notificaciones', 'icono')
    op.drop_column('notificaciones', 'mensaje_id')
    op.alter_column('periodos_academicos', 'codigo',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('periodos_academicos', 'moneda',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'COP'::character varying"))
    op.drop_index(op.f('ix_periodos_academicos_institucion_activo'), table_name='periodos_academicos')
    op.drop_index(op.f('ix_periodos_academicos_institucion_anio'), table_name='periodos_academicos')
    op.drop_constraint(op.f('uq_periodo_codigo'), 'periodos_academicos', type_='unique')
    op.create_index(op.f('ix_periodos_academicos_codigo'), 'periodos_academicos', ['codigo'], unique=True)
    op.drop_constraint(op.f('periodos_academicos_institucion_id_fkey'), 'periodos_academicos', type_='foreignkey')
    op.create_foreign_key(None, 'periodos_academicos', 'Institucion', ['institucion_id'], ['institucion_id'])
    op.alter_column('preguntas_examen', 'tipo_pregunta',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('OPCION_MULTIPLE', 'VERDADERO_FALSO', 'ENSAYO', 'RESPUESTA_CORTA', 'COMPLETAR', 'EMPAREJAMIENTO', 'ORDENAMIENTO', name='tipopregunta'),
               existing_nullable=False)
    op.alter_column('preguntas_examen', 'dificultad',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('MUY_FACIL', 'FACIL', 'MEDIO', 'DIFICIL', 'MUY_DIFICIL', name='dificultadpregunta'),
               existing_nullable=True,
               existing_server_default=sa.text("'medio'::character varying"))
    op.create_foreign_key(None, 'rubricas', 'Usuario', ['creado_por'], ['usuario_id'])
    op.add_column('salas_chat', sa.Column('requiere_aprobacion', sa.Boolean(), nullable=True))
    op.add_column('salas_chat', sa.Column('max_participantes', sa.Integer(), nullable=True))
    op.add_column('salas_chat', sa.Column('esta_activa', sa.Boolean(), nullable=True))
    op.add_column('salas_chat', sa.Column('fecha_ultima_actividad', sa.DateTime(), nullable=True))
    op.add_column('salas_chat', sa.Column('total_mensajes', sa.Integer(), nullable=True))
    op.add_column('salas_chat', sa.Column('configuracion', sa.JSON(), nullable=True))
    op.alter_column('salas_chat', 'tipo_sala',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('CURSO', 'GRUPO', 'TAREA', 'PRIVADO', 'GENERAL', name='tiposala'),
               existing_nullable=False)
    op.create_foreign_key(None, 'salas_chat', 'Usuario', ['creador_id'], ['usuario_id'])
    op.drop_column('salas_chat', 'moderacion_activa')
    op.drop_column('salas_chat', 'permite_hilos')
    op.drop_column('salas_chat', 'configuracion_json')
    op.drop_column('salas_chat', 'permite_menciones')
    op.drop_column('salas_chat', 'ultimo_mensaje_fecha')
    op.drop_column('salas_chat', 'tags')
    op.add_column('tareas', sa.Column('categoria', sa.String(length=100), nullable=True))
    op.alter_column('tareas', 'grupo_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('tareas', 'docente_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('tareas', 'tipo_tarea',
               existing_type=postgresql.ENUM('ensayo', 'proyecto', 'ejercicios', 'investigacion', 'presentacion', 'laboratorio', 'lectura', 'examen', 'otro', name='tipo_tarea'),
               type_=sa.Enum('ENSAYO', 'PROYECTO', 'EJERCICIOS', 'INVESTIGACION', 'PRESENTACION', 'LABORATORIO', 'LECTURA', 'EXAMEN', 'OTRO', name='tipotarea'),
               existing_nullable=False,
               existing_server_default=sa.text("'ensayo'::tipo_tarea"))
    op.alter_column('tareas', 'prioridad',
               existing_type=postgresql.ENUM('baja', 'media', 'alta', 'urgente', name='prioridad_tarea'),
               type_=sa.Enum('BAJA', 'MEDIA', 'ALTA', 'URGENTE', name='prioridadtarea'),
               existing_nullable=False,
               existing_server_default=sa.text("'media'::prioridad_tarea"))
    op.alter_column('tareas', 'estado',
               existing_type=postgresql.ENUM('asignada', 'en_progreso', 'entregada', 'calificada', 'vencida', 'cancelada', name='estado_tarea'),
               type_=sa.Enum('ASIGNADA', 'EN_PROGRESO', 'ENTREGADA', 'CALIFICADA', 'VENCIDA', 'CANCELADA', name='estadotarea'),
               existing_nullable=False,
               existing_server_default=sa.text("'asignada'::estado_tarea"))
    op.alter_column('tareas', 'creado_por',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tareas', 'actualizado_por',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_tareas_docente_id'), table_name='tareas')
    op.drop_index(op.f('idx_tareas_estado'), table_name='tareas')
    op.drop_index(op.f('idx_tareas_fecha_limite'), table_name='tareas')
    op.drop_index(op.f('idx_tareas_grupo_id'), table_name='tareas')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_tareas_grupo_id'), 'tareas', ['grupo_id'], unique=False)
    op.create_index(op.f('idx_tareas_fecha_limite'), 'tareas', ['fecha_limite'], unique=False)
    op.create_index(op.f('idx_tareas_estado'), 'tareas', ['estado'], unique=False)
    op.create_index(op.f('idx_tareas_docente_id'), 'tareas', ['docente_id'], unique=False)
    op.alter_column('tareas', 'actualizado_por',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('tareas', 'creado_por',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('tareas', 'estado',
               existing_type=sa.Enum('ASIGNADA', 'EN_PROGRESO', 'ENTREGADA', 'CALIFICADA', 'VENCIDA', 'CANCELADA', name='estadotarea'),
               type_=postgresql.ENUM('asignada', 'en_progreso', 'entregada', 'calificada', 'vencida', 'cancelada', name='estado_tarea'),
               existing_nullable=False,
               existing_server_default=sa.text("'asignada'::estado_tarea"))
    op.alter_column('tareas', 'prioridad',
               existing_type=sa.Enum('BAJA', 'MEDIA', 'ALTA', 'URGENTE', name='prioridadtarea'),
               type_=postgresql.ENUM('baja', 'media', 'alta', 'urgente', name='prioridad_tarea'),
               existing_nullable=False,
               existing_server_default=sa.text("'media'::prioridad_tarea"))
    op.alter_column('tareas', 'tipo_tarea',
               existing_type=sa.Enum('ENSAYO', 'PROYECTO', 'EJERCICIOS', 'INVESTIGACION', 'PRESENTACION', 'LABORATORIO', 'LECTURA', 'EXAMEN', 'OTRO', name='tipotarea'),
               type_=postgresql.ENUM('ensayo', 'proyecto', 'ejercicios', 'investigacion', 'presentacion', 'laboratorio', 'lectura', 'examen', 'otro', name='tipo_tarea'),
               existing_nullable=False,
               existing_server_default=sa.text("'ensayo'::tipo_tarea"))
    op.alter_column('tareas', 'docente_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('tareas', 'grupo_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_column('tareas', 'categoria')
    op.add_column('salas_chat', sa.Column('tags', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('salas_chat', sa.Column('ultimo_mensaje_fecha', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('salas_chat', sa.Column('permite_menciones', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('salas_chat', sa.Column('configuracion_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('salas_chat', sa.Column('permite_hilos', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('salas_chat', sa.Column('moderacion_activa', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'salas_chat', type_='foreignkey')
    op.alter_column('salas_chat', 'tipo_sala',
               existing_type=sa.Enum('CURSO', 'GRUPO', 'TAREA', 'PRIVADO', 'GENERAL', name='tiposala'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('salas_chat', 'configuracion')
    op.drop_column('salas_chat', 'total_mensajes')
    op.drop_column('salas_chat', 'fecha_ultima_actividad')
    op.drop_column('salas_chat', 'esta_activa')
    op.drop_column('salas_chat', 'max_participantes')
    op.drop_column('salas_chat', 'requiere_aprobacion')
    op.drop_constraint(None, 'rubricas', type_='foreignkey')
    op.alter_column('preguntas_examen', 'dificultad',
               existing_type=sa.Enum('MUY_FACIL', 'FACIL', 'MEDIO', 'DIFICIL', 'MUY_DIFICIL', name='dificultadpregunta'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'medio'::character varying"))
    op.alter_column('preguntas_examen', 'tipo_pregunta',
               existing_type=sa.Enum('OPCION_MULTIPLE', 'VERDADERO_FALSO', 'ENSAYO', 'RESPUESTA_CORTA', 'COMPLETAR', 'EMPAREJAMIENTO', 'ORDENAMIENTO', name='tipopregunta'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_constraint(None, 'periodos_academicos', type_='foreignkey')
    op.create_foreign_key(op.f('periodos_academicos_institucion_id_fkey'), 'periodos_academicos', 'Institucion', ['institucion_id'], ['institucion_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_periodos_academicos_codigo'), table_name='periodos_academicos')
    op.create_unique_constraint(op.f('uq_periodo_codigo'), 'periodos_academicos', ['codigo'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_periodos_academicos_institucion_anio'), 'periodos_academicos', ['institucion_id', 'anio'], unique=False)
    op.create_index(op.f('ix_periodos_academicos_institucion_activo'), 'periodos_academicos', ['institucion_id', 'activo'], unique=False)
    op.alter_column('periodos_academicos', 'moneda',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'COP'::character varying"))
    op.alter_column('periodos_academicos', 'codigo',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.add_column('notificaciones', sa.Column('mensaje_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('notificaciones', sa.Column('icono', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('notificaciones', sa.Column('color', sa.VARCHAR(length=7), autoincrement=False, nullable=True))
    op.add_column('notificaciones', sa.Column('url_accion', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('notificaciones', sa.Column('curso_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('notificaciones', sa.Column('tarea_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('notificaciones', sa.Column('tipo_notificacion', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('notificaciones', sa.Column('sala_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'notificaciones', type_='foreignkey')
    op.create_foreign_key(op.f('notificaciones_sala_id_fkey'), 'notificaciones', 'salas_chat', ['sala_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('notificaciones_mensaje_id_fkey'), 'notificaciones', 'mensajes', ['mensaje_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_notificaciones_usuario_leida_fecha'), 'notificaciones', ['usuario_id', 'leida', sa.literal_column('fecha_creacion DESC')], unique=False)
    op.create_index(op.f('idx_notificaciones_usuario_id'), 'notificaciones', ['usuario_id'], unique=False)
    op.create_index(op.f('idx_notificaciones_tipo'), 'notificaciones', ['tipo_notificacion'], unique=False, postgresql_where='(tipo_notificacion IS NOT NULL)')
    op.create_index(op.f('idx_notificaciones_leida'), 'notificaciones', ['leida'], unique=False)
    op.drop_column('notificaciones', 'referencia_tipo')
    op.drop_column('notificaciones', 'referencia_id')
    op.drop_column('notificaciones', 'tipo')
    op.add_column('mensajes', sa.Column('metadatos_archivos', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('mensajes', sa.Column('numero_respuestas', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('mensajes', sa.Column('contenido', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('mensajes', sa.Column('menciones_ia', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('mensajes', sa.Column('fecha_actualizacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('mensajes', sa.Column('menciones_usuarios', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('mensajes', sa.Column('archivos_urls', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('mensajes', sa.Column('menciones_todos', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('mensajes', sa.Column('fecha_eliminacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('mensajes', sa.Column('contenido_html', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('mensajes', sa.Column('tiene_respuestas', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'mensajes', type_='foreignkey')
    op.drop_constraint(None, 'mensajes', type_='foreignkey')
    op.drop_constraint(None, 'mensajes', type_='foreignkey')
    op.create_foreign_key(op.f('mensajes_sala_id_fkey'), 'mensajes', 'salas_chat', ['sala_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('mensajes_mensaje_padre_id_fkey'), 'mensajes', 'mensajes', ['mensaje_padre_id'], ['id'], ondelete='CASCADE')
    op.alter_column('mensajes', 'estado',
               existing_type=sa.Enum('ENVIADO', 'ENTREGADO', 'LEIDO', 'EDITADO', 'ELIMINADO', name='estadomensaje'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('mensajes', 'tipo_mensaje',
               existing_type=sa.Enum('TEXTO', 'IMAGEN', 'ARCHIVO', 'AUDIO', 'VIDEO', 'ENLACE', 'SISTEMA', 'IA', name='tipomensaje'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('mensajes', 'programado_para')
    op.drop_column('mensajes', 'menciones')
    op.drop_column('mensajes', 'total_respuestas')
    op.drop_column('mensajes', 'es_respuesta')
    op.drop_column('mensajes', 'editado_por')
    op.drop_column('mensajes', 'fecha_edicion')
    op.drop_column('mensajes', 'datos_adjuntos')
    op.drop_column('mensajes', 'texto')
    op.drop_constraint(None, 'intentos_examen', type_='foreignkey')
    op.drop_constraint(None, 'intentos_examen', type_='foreignkey')
    op.alter_column('intentos_examen', 'revisado_por',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('intentos_examen', 'estado_intento',
               existing_type=sa.Enum('EN_PROGRESO', 'FINALIZADO', 'TIEMPO_AGOTADO', 'CANCELADO', 'ABANDONADO', name='estadointento'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'en_progreso'::character varying"))
    op.alter_column('intentos_examen', 'estudiante_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.add_column('inscripciones', sa.Column('fecha_preinscripcion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'inscripciones', type_='foreignkey')
    op.drop_constraint(None, 'inscripciones', type_='foreignkey')
    op.drop_constraint(None, 'inscripciones', type_='foreignkey')
    op.drop_constraint(None, 'inscripciones', type_='foreignkey')
    op.drop_constraint(None, 'inscripciones', type_='foreignkey')
    op.drop_constraint(None, 'inscripciones', type_='foreignkey')
    op.drop_constraint(None, 'inscripciones', type_='foreignkey')
    op.drop_constraint(None, 'inscripciones', type_='foreignkey')
    op.create_foreign_key(op.f('inscripciones_rechazada_por_id_fkey'), 'inscripciones', 'Usuario', ['rechazada_por_id'], ['usuario_id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('inscripciones_programa_id_fkey'), 'inscripciones', 'Programa', ['programa_id'], ['programa_id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('inscripciones_aprobada_por_id_fkey'), 'inscripciones', 'Usuario', ['aprobada_por_id'], ['usuario_id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('inscripciones_grupo_id_fkey'), 'inscripciones', 'Grupo', ['grupo_id'], ['grupo_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('inscripciones_modificado_por_id_fkey'), 'inscripciones', 'Usuario', ['modificado_por_id'], ['usuario_id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('inscripciones_estudiante_id_fkey'), 'inscripciones', 'Usuario', ['estudiante_id'], ['usuario_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('inscripciones_creado_por_id_fkey'), 'inscripciones', 'Usuario', ['creado_por_id'], ['usuario_id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('inscripciones_periodo_academico_id_fkey'), 'inscripciones', 'periodos_academicos', ['periodo_academico_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_inscripciones_codigo_inscripcion'), table_name='inscripciones')
    op.create_index(op.f('ix_inscripciones_codigo_inscripcion'), 'inscripciones', ['codigo_inscripcion'], unique=False)
    op.create_unique_constraint(op.f('uq_inscripcion_codigo'), 'inscripciones', ['codigo_inscripcion'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_inscripciones_tipo_inscripcion'), 'inscripciones', ['tipo_inscripcion'], unique=False)
    op.create_index(op.f('ix_inscripciones_periodo_estado'), 'inscripciones', ['periodo_academico_id', 'estado'], unique=False)
    op.create_index(op.f('ix_inscripciones_lista_espera'), 'inscripciones', ['grupo_id', 'en_lista_espera', 'posicion_lista_espera'], unique=False)
    op.create_index(op.f('ix_inscripciones_grupo_estado'), 'inscripciones', ['grupo_id', 'estado'], unique=False)
    op.create_index(op.f('ix_inscripciones_grupo_activas'), 'inscripciones', ['grupo_id', 'activo', 'estado'], unique=False)
    op.create_index(op.f('ix_inscripciones_fecha_creacion'), 'inscripciones', ['fecha_creacion'], unique=False)
    op.create_index(op.f('ix_inscripciones_estudiante_grupo'), 'inscripciones', ['estudiante_id', 'grupo_id'], unique=False)
    op.create_index(op.f('ix_inscripciones_estudiante_activo'), 'inscripciones', ['estudiante_id', 'activo'], unique=False)
    op.create_index(op.f('ix_inscripciones_esta_pagado'), 'inscripciones', ['esta_pagado'], unique=False)
    op.create_index(op.f('ix_inscripciones_esta_aprobada'), 'inscripciones', ['esta_aprobada'], unique=False)
    op.create_index(op.f('ix_inscripciones_en_lista_espera'), 'inscripciones', ['en_lista_espera'], unique=False)
    op.alter_column('inscripciones', 'motivo_atencion',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.alter_column('inscripciones', 'calificacion_final',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=4, scale=2),
               existing_nullable=True)
    op.alter_column('inscripciones', 'monto_final',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('inscripciones', 'descuentos',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('inscripciones', 'otros_costos',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('inscripciones', 'costo_curso',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('inscripciones', 'costo_matricula',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('inscripciones', 'costo_total',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
    op.alter_column('inscripciones', 'fecha_limite_confirmacion',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('inscripciones', 'fecha_limite_documentos',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('inscripciones', 'fecha_limite_pago',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('inscripciones', 'fecha_inicio_clases',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('inscripciones', 'fecha_solicitud',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('inscripciones', 'periodo_academico_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('inscripciones', 'fecha_pre_inscripcion')
    op.drop_constraint(None, 'examenes', type_='foreignkey')
    op.alter_column('examenes', 'creado_por',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('examenes', 'grupo_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('examenes', 'curso_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('examenes', 'estado_examen',
               existing_type=sa.Enum('BORRADOR', 'PUBLICADO', 'ACTIVO', 'FINALIZADO', 'ARCHIVADO', name='estadoexamen'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'borrador'::character varying"))
    op.alter_column('examenes', 'tipo_examen',
               existing_type=sa.Enum('EVALUACION', 'PRUEBA', 'EXAMEN_FINAL', 'QUIZ', 'SIMULACRO', 'DIAGNOSTICO', name='tipoexamen'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'evaluacion'::character varying"))
    op.alter_column('eventos_anti_trampa', 'tipo_evento',
               existing_type=sa.Enum('CAMBIO_PESTANA', 'CAMBIO_APLICACION', 'CLIC_FUERA_VENTANA', 'TIEMPO_INACTIVO', 'PANTALLA_COMPLETA_SALIDA', 'TECLAS_SOSPECHOSAS', 'MULTIPLE_SESION_IP', 'PATRON_RESPUESTA_SOSPECHOSO', 'VELOCIDAD_RESPUESTA_ANOMALA', name='tipoevento'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.create_index(op.f('idx_entregas_tarea_id'), 'entregas_tareas', ['tarea_id'], unique=False)
    op.create_index(op.f('idx_entregas_estudiante_id'), 'entregas_tareas', ['estudiante_id'], unique=False)
    op.create_index(op.f('idx_entregas_estado'), 'entregas_tareas', ['estado'], unique=False)
    op.alter_column('entregas_tareas', 'calificado_por',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('entregas_tareas', 'estudiante_id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_constraint(None, 'configuracion_evaluaciones', type_='foreignkey')
    op.alter_column('configuracion_evaluaciones', 'creado_por',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('configuracion_evaluaciones', 'institucion_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_constraint(None, 'banco_preguntas', type_='foreignkey')
    op.alter_column('banco_preguntas', 'revisado_por',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('banco_preguntas', 'institucion_id',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('banco_preguntas', 'dificultad',
               existing_type=sa.Enum('MUY_FACIL', 'FACIL', 'MEDIO', 'DIFICIL', 'MUY_DIFICIL', name='dificultadpregunta'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'medio'::character varying"))
    op.alter_column('banco_preguntas', 'tipo_pregunta',
               existing_type=sa.Enum('OPCION_MULTIPLE', 'VERDADERO_FALSO', 'ENSAYO', 'RESPUESTA_CORTA', 'COMPLETAR', 'EMPAREJAMIENTO', 'ORDENAMIENTO', name='tipopregunta'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.create_index(op.f('idx_usuario_puntos_usuario_id'), 'UsuarioPuntos', ['usuario_id'], unique=False)
    op.create_index(op.f('idx_insignias_usuario_usuario_id'), 'UsuarioInsignia', ['usuario_id'], unique=False)
    op.create_index(op.f('idx_usuario_rol_estado'), 'Usuario', ['rol', 'estado_cuenta'], unique=False)
    op.create_index(op.f('idx_usuario_rol'), 'Usuario', ['rol'], unique=False)
    op.create_index(op.f('idx_usuario_nombres_busqueda'), 'Usuario', [sa.literal_column("to_tsvector('spanish'::regconfig, (nombres::text || ' '::text) || apellidos::text)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_usuario_estado_cuenta'), 'Usuario', ['estado_cuenta'], unique=False)
    op.drop_constraint('uq_programa_codigo', 'Programa', type_='unique')
    op.drop_index('idx_programa_institucion', table_name='Programa')
    op.create_index(op.f('idx_programa_coordinador'), 'Programa', ['coordinador_id'], unique=False)
    op.create_index(op.f('idx_programa_codigo'), 'Programa', ['codigo'], unique=True)
    op.alter_column('Programa', 'nombre',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_constraint(None, 'MaterialEducativo', type_='foreignkey')
    op.drop_constraint(None, 'MaterialEducativo', type_='foreignkey')
    op.drop_index('idx_material_original', table_name='MaterialEducativo')
    op.drop_index('idx_material_fecha', table_name='MaterialEducativo')
    op.drop_index('idx_material_estado', table_name='MaterialEducativo')
    op.drop_index('idx_material_carpeta', table_name='MaterialEducativo')
    op.alter_column('MaterialEducativo', 'formato_archivo',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('MaterialEducativo', 'url_archivo',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('MaterialEducativo', 'titulo',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.drop_column('MaterialEducativo', 'fecha_actualizacion')
    op.drop_column('MaterialEducativo', 'fecha_creacion')
    op.drop_column('MaterialEducativo', 'fecha_ultimo_acceso')
    op.drop_column('MaterialEducativo', 'numero_descargas')
    op.drop_column('MaterialEducativo', 'fecha_ultima_sync')
    op.drop_column('MaterialEducativo', 'sincronizado_drive')
    op.drop_column('MaterialEducativo', 'google_drive_url')
    op.drop_column('MaterialEducativo', 'google_drive_id')
    op.drop_column('MaterialEducativo', 'tags')
    op.drop_column('MaterialEducativo', 'autor_id')
    op.drop_column('MaterialEducativo', 'es_version_actual')
    op.drop_column('MaterialEducativo', 'material_original_id')
    op.drop_column('MaterialEducativo', 'version')
    op.drop_column('MaterialEducativo', 'hash_archivo')
    op.drop_column('MaterialEducativo', 'tamano_archivo')
    op.drop_column('MaterialEducativo', 'estado')
    op.drop_column('MaterialEducativo', 'carpeta')
    op.create_index(op.f('idx_material_curso_curso_id'), 'MaterialCurso', ['curso_id'], unique=False)
    op.alter_column('MaterialCurso', 'curso_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('idx_material_clase_clase_id'), 'MaterialClase', ['clase_id'], unique=False)
    op.alter_column('Institucion', 'estado',
               existing_type=postgresql.ENUM('pendiente', 'activa', 'suspendida', 'inactiva', name='estado_institucion'),
               comment='Estado del ciclo de vida: pendiente → activa → suspendida/inactiva',
               existing_comment='Estado del ciclo de vida: pendiente (sin coordinador) → activa (operando) → suspendida/inactiva',
               existing_nullable=False,
               existing_server_default=sa.text("'pendiente'::estado_institucion"))
    op.alter_column('Institucion', 'campos_personalizados',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Campos personalizados específicos',
               existing_comment='Campos personalizados específicos de la institución (ej: {"codigo_DANE": "123456", "regimen_especial": true})',
               existing_nullable=True)
    op.alter_column('Institucion', 'configuracion_regional',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Configuración regional',
               existing_comment='Configuración regional: {"idioma": "es", "zona_horaria": "America/Bogota", "moneda": "COP", "formato_fecha": "DD/MM/YYYY"}',
               existing_nullable=True)
    op.alter_column('Institucion', 'acreditacion_internacional',
               existing_type=sa.VARCHAR(length=150),
               comment='Certificaciones internacionales',
               existing_comment='Certificaciones internacionales (ej: ISO 9001, QS Stars)',
               existing_nullable=True)
    op.alter_column('Institucion', 'acreditacion_nacional',
               existing_type=sa.VARCHAR(length=150),
               comment='Entidad acreditadora nacional',
               existing_comment='Entidad acreditadora nacional (ej: MEN Colombia, SEP México)',
               existing_nullable=True)
    op.alter_column('Institucion', 'redes_sociales',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='JSON con links a redes sociales',
               existing_comment='JSON con links a redes sociales: {"facebook": "url", "instagram": "url", "linkedin": "url"}',
               existing_nullable=True)
    op.alter_column('Institucion', 'dominios_adicionales',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               comment='Dominios secundarios para registro automático',
               existing_comment='Dominios secundarios para registro automático (ej: ["alumni.arp.edu.co", "docentes.arp.edu.co"])',
               existing_nullable=True)
    op.alter_column('Institucion', 'jornadas',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               comment='Array de jornadas disponibles',
               existing_comment='Array de jornadas disponibles: ["mañana", "tarde", "noche", "fines_de_semana"]',
               existing_nullable=True)
    op.alter_column('Institucion', 'tipo_calendario',
               existing_type=postgresql.ENUM('semestral', 'trimestral', 'bimestral', 'cuatrimestral', 'anual', 'modular', name='tipo_calendario'),
               comment='Tipo de calendario académico',
               existing_comment='Tipo de calendario académico (semestral, trimestral, etc.)',
               existing_nullable=True)
    op.alter_column('Institucion', 'color_secundario',
               existing_type=sa.VARCHAR(length=7),
               comment='Color secundario en formato hexadecimal #RRGGBB',
               existing_comment='Color secundario en formato hexadecimal #RRGGBB (opcional)',
               existing_nullable=True)
    op.alter_column('Institucion', 'color_primario',
               existing_type=sa.VARCHAR(length=7),
               comment='Color primario en formato hexadecimal #RRGGBB',
               existing_comment='Color primario en formato hexadecimal #RRGGBB (opcional)',
               existing_nullable=True)
    op.create_index(op.f('idx_grupo_curso_docente_id'), 'GrupoCurso', ['docente_id'], unique=False)
    op.create_index(op.f('idx_grupo_curso_curso_id'), 'GrupoCurso', ['curso_id'], unique=False)
    op.drop_index(op.f('ix_Grupo_periodo_academico_id'), table_name='Grupo')
    op.create_index(op.f('idx_grupo_tipo'), 'Grupo', ['tipo_grupo'], unique=False)
    op.create_index(op.f('idx_grupo_periodo'), 'Grupo', ['periodo_academico_id'], unique=False)
    op.create_unique_constraint(op.f('Grupo_docente_tutor_id_key'), 'Grupo', ['docente_tutor_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('Grupo', 'nombre',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('Grupo', 'programa_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('idx_estudiante_grupo_grupo_id'), 'EstudianteGrupo', ['grupo_id'], unique=False)
    op.create_index(op.f('idx_estudiante_grupo_estudiante_id'), 'EstudianteGrupo', ['estudiante_id'], unique=False)
    op.create_index(op.f('idx_estudiante_grupo_estudiante_grupo'), 'EstudianteGrupo', ['estudiante_id', 'grupo_id'], unique=False)
    op.drop_index('idx_curso_programa', table_name='Curso')
    op.drop_index('idx_curso_institucion', table_name='Curso')
    op.drop_index('idx_curso_fechas', table_name='Curso')
    op.drop_index('idx_curso_coordinador', table_name='Curso')
    op.create_index(op.f('idx_curso_tipo'), 'Curso', ['tipo_curso'], unique=False)
    op.create_index(op.f('idx_curso_programa_id'), 'Curso', ['programa_id'], unique=False)
    op.create_index(op.f('idx_curso_nivel_dificultad'), 'Curso', ['nivel_dificultad'], unique=False)
    op.create_index(op.f('idx_curso_institucion_programa'), 'Curso', ['institucion_id', 'programa_id'], unique=False)
    op.create_index(op.f('idx_curso_institucion_id'), 'Curso', ['institucion_id'], unique=False)
    op.create_index(op.f('idx_curso_estado'), 'Curso', ['estado'], unique=False)
    op.create_index(op.f('idx_curso_coordinador_id'), 'Curso', ['coordinador_id'], unique=False, postgresql_where='(coordinador_id IS NOT NULL)')
    op.create_index(op.f('idx_curso_codigo_acceso'), 'Curso', ['codigo_acceso'], unique=True)
    op.create_index(op.f('idx_curso_categoria'), 'Curso', ['categoria_curso'], unique=False)
    op.alter_column('Curso', 'requiere_aprobacion_material',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('Curso', 'permite_material_estudiantes',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('Curso', 'codigo_acceso',
               existing_type=sa.VARCHAR(length=10),
               comment='Código para que estudiantes se unan',
               existing_nullable=True)
    op.alter_column('Curso', 'codigo_curso',
               existing_type=sa.VARCHAR(length=20),
               comment='Código identificador del curso (ej: MAT101)',
               existing_nullable=True)
    op.alter_column('Curso', 'nombre',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('Curso', 'programa_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_Comentario_tipo'), table_name='Comentario')
    op.drop_index(op.f('ix_Comentario_fecha_creacion'), table_name='Comentario')
    op.drop_index(op.f('ix_Comentario_esta_eliminado'), table_name='Comentario')
    op.drop_index(op.f('ix_Comentario_curso_id'), table_name='Comentario')
    op.drop_index(op.f('ix_Comentario_comentario_padre_id'), table_name='Comentario')
    op.drop_index(op.f('ix_Comentario_comentario_id'), table_name='Comentario')
    op.drop_index(op.f('ix_Comentario_autor_id'), table_name='Comentario')
    op.drop_index(op.f('ix_Comentario_activo'), table_name='Comentario')
    op.create_index(op.f('idx_comentarios_padre_id'), 'Comentario', ['comentario_padre_id'], unique=False, postgresql_where='(comentario_padre_id IS NOT NULL)')
    op.create_index(op.f('idx_comentarios_fecha_creacion'), 'Comentario', [sa.literal_column('fecha_creacion DESC')], unique=False)
    op.create_index(op.f('idx_comentarios_curso_tipo_fecha'), 'Comentario', ['curso_id', 'tipo', sa.literal_column('fecha_creacion DESC')], unique=False, postgresql_where='(comentario_padre_id IS NULL)')
    op.create_index(op.f('idx_comentarios_curso_id'), 'Comentario', ['curso_id'], unique=False, postgresql_where='(comentario_padre_id IS NULL)')
    op.create_index(op.f('idx_comentarios_autor_id'), 'Comentario', ['autor_id'], unique=False)
    op.create_index(op.f('idx_comentario_tipo_activo'), 'Comentario', ['tipo', 'activo'], unique=False)
    op.create_index(op.f('idx_comentario_tipo'), 'Comentario', ['tipo'], unique=False)
    op.create_index(op.f('idx_comentario_padre'), 'Comentario', ['comentario_padre_id'], unique=False)
    op.create_index(op.f('idx_comentario_fecha_creacion'), 'Comentario', ['fecha_creacion'], unique=False)
    op.create_index(op.f('idx_comentario_curso_id'), 'Comentario', ['curso_id'], unique=False)
    op.create_index(op.f('idx_comentario_curso_fecha'), 'Comentario', ['curso_id', 'fecha_creacion'], unique=False)
    op.create_index(op.f('idx_comentario_autor_id'), 'Comentario', ['autor_id'], unique=False)
    op.create_index(op.f('idx_comentario_autor_fecha'), 'Comentario', ['autor_id', 'fecha_creacion'], unique=False)
    op.create_index(op.f('idx_comentario_activo'), 'Comentario', ['activo'], unique=False)
    op.alter_column('Comentario', 'archivos_adjuntos',
               existing_type=sa.Text(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('Clase', sa.Column('grupo_curso_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('Clase', sa.Column('hora_inicio', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('Clase', sa.Column('link_videollamada', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('Clase', sa.Column('plataforma_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('Clase', sa.Column('duracion', postgresql.INTERVAL(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'Clase', type_='foreignkey')
    op.drop_constraint(None, 'Clase', type_='foreignkey')
    op.create_foreign_key(op.f('Clase_plataforma_id_fkey'), 'Clase', 'Plataforma', ['plataforma_id'], ['plataforma_id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('Clase_grupo_curso_id_fkey'), 'Clase', 'GrupoCurso', ['grupo_curso_id'], ['grupo_curso_id'], ondelete='CASCADE')
    op.drop_constraint(None, 'Clase', type_='unique')
    op.drop_index('idx_clase_fecha', table_name='Clase')
    op.drop_index('idx_clase_docente_grupo', table_name='Clase')
    op.drop_index('idx_clase_codigo_acceso', table_name='Clase')
    op.alter_column('Clase', 'titulo',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('Clase', 'fecha_actualizacion')
    op.drop_column('Clase', 'fecha_creacion')
    op.drop_column('Clase', 'max_estudiantes')
    op.drop_column('Clase', 'fecha_vencimiento_codigo')
    op.drop_column('Clase', 'estado_codigo')
    op.drop_column('Clase', 'codigo_acceso')
    op.drop_column('Clase', 'duracion_estimada')
    op.drop_column('Clase', 'fecha_fin')
    op.drop_column('Clase', 'fecha_inicio')
    op.drop_column('Clase', 'estado')
    op.drop_column('Clase', 'tipo_clase')
    op.drop_column('Clase', 'docente_id')
    op.drop_column('Clase', 'grupo_id')
    op.create_table('Reacciones',
    sa.Column('reaccion_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('comentario_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('usuario_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('emoji', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.Column('activo', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['comentario_id'], ['Comentario.comentario_id'], name=op.f('Reacciones_comentario_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['Usuario.usuario_id'], name=op.f('Reacciones_usuario_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('reaccion_id', name=op.f('Reacciones_pkey')),
    sa.UniqueConstraint('comentario_id', 'usuario_id', 'emoji', name=op.f('uq_user_emoji_per_comment'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_reacciones_usuario_id'), 'Reacciones', ['usuario_id'], unique=False)
    op.create_index(op.f('idx_reacciones_emoji'), 'Reacciones', ['emoji'], unique=False)
    op.create_index(op.f('idx_reacciones_comentario_usuario'), 'Reacciones', ['comentario_id', 'usuario_id'], unique=False)
    op.create_index(op.f('idx_reacciones_comentario_id'), 'Reacciones', ['comentario_id'], unique=False)
    op.create_index(op.f('idx_reacciones_activo'), 'Reacciones', ['activo'], unique=False)
    op.create_table('invitation_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('email_destino', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('institucion_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('estado', postgresql.ENUM('pendiente', 'usado', 'expirado', name='estado_invitacion'), server_default=sa.text("'pendiente'::estado_invitacion"), autoincrement=False, nullable=False),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('fecha_expiracion', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('coordinador_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('usado_en', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['coordinador_id'], ['Usuario.usuario_id'], name=op.f('invitation_tokens_coordinador_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institucion_id'], ['Institucion.institucion_id'], name=op.f('invitation_tokens_institucion_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('invitation_tokens_pkey')),
    sa.UniqueConstraint('codigo', name=op.f('invitation_tokens_codigo_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_invitation_tokens_id'), 'invitation_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_invitation_tokens_codigo'), 'invitation_tokens', ['codigo'], unique=True)
    op.drop_table('EntregarTarea')
    op.drop_table('Tarea')
    op.drop_table('Mensaje')
    op.drop_index('idx_historial_fecha_acceso', table_name='HistorialAccesoClase')
    op.drop_index('idx_historial_clase_estudiante', table_name='HistorialAccesoClase')
    op.drop_table('HistorialAccesoClase')
    op.drop_table('lecturas_mensajes')
    op.drop_table('participantes_sala')
    op.drop_table('configuracion_notificaciones')
    # ### end Alembic commands ###
