"""add_gender_fields_to_avatars

Revision ID: a5664b066656
Revises: a1b2c3d4e5f6
Create Date: 2025-09-22 23:30:17.776193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5664b066656'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invitation_tokens_codigo'), table_name='invitation_tokens')
    op.drop_table('invitation_tokens')
    # Comentado: problemas con primary key
    # op.alter_column('MaterialCurso', 'curso_id',
    #            existing_type=sa.UUID(),
    #            nullable=True)
    op.add_column('avatar_asset', sa.Column('target_gender', sa.String(length=20), server_default=sa.text("'unisex'"), nullable=False))
    op.create_index(op.f('ix_avatar_asset_target_gender'), 'avatar_asset', ['target_gender'], unique=False)
    op.drop_table_comment(
        'avatar_asset',
        existing_comment='Assets disponibles para construcción de avatars',
        schema=None
    )
    op.add_column('user_avatar', sa.Column('base_gender', sa.String(length=20), server_default=sa.text("'male'"), nullable=False))
    op.drop_constraint(op.f('uk_user_avatar_active_per_user'), 'user_avatar', type_='unique')
    op.drop_table_comment(
        'user_avatar',
        existing_comment='Avatars creados y guardados por usuarios',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'user_avatar',
        'Avatars creados y guardados por usuarios',
        existing_comment=None,
        schema=None
    )
    op.create_unique_constraint(op.f('uk_user_avatar_active_per_user'), 'user_avatar', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('user_avatar', 'base_gender')
    op.create_table_comment(
        'avatar_asset',
        'Assets disponibles para construcción de avatars',
        existing_comment=None,
        schema=None
    )
    op.drop_index(op.f('ix_avatar_asset_target_gender'), table_name='avatar_asset')
    op.drop_column('avatar_asset', 'target_gender')
    # Comentado: problemas con primary key
    # op.alter_column('MaterialCurso', 'curso_id',
    #            existing_type=sa.UUID(),
    #            nullable=False)
    op.create_table('invitation_tokens',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('email_destino', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('institucion_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('estado', postgresql.ENUM('pendiente', 'usado', 'expirado', name='estado_invitacion'), server_default=sa.text("'pendiente'::estado_invitacion"), autoincrement=False, nullable=False),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('fecha_expiracion', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('coordinador_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('usado_en', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['coordinador_id'], ['Usuario.usuario_id'], name=op.f('invitation_tokens_coordinador_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institucion_id'], ['Institucion.institucion_id'], name=op.f('invitation_tokens_institucion_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('invitation_tokens_pkey'))
    )
    op.create_index(op.f('ix_invitation_tokens_codigo'), 'invitation_tokens', ['codigo'], unique=True)
    # ### end Alembic commands ###
