"""FK administrador_id_creador ahora apunta a Usuario y fix telefono

Revision ID: b0a5a4d8a398
Revises: add_invitation_tokens
Create Date: 2025-09-18 18:19:27.707304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0a5a4d8a398'
down_revision: Union[str, Sequence[str], None] = 'add_invitation_tokens'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Institucion', 'telefono',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.drop_constraint(op.f('Institucion_administrador_id_creador_fkey'), 'Institucion', type_='foreignkey')
    op.create_foreign_key(None, 'Institucion', 'Usuario', ['administrador_id_creador'], ['usuario_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Institucion', type_='foreignkey')
    op.create_foreign_key(op.f('Institucion_administrador_id_creador_fkey'), 'Institucion', 'AdministradorSistema', ['administrador_id_creador'], ['administrador_id'], ondelete='SET NULL')
    op.alter_column('Institucion', 'telefono',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=25),
               existing_nullable=False)
    # ### end Alembic commands ###
