"""Restaurar campos estado y fechas a Institucion

Revision ID: fc4e3b4225a5
Revises: b0a5a4d8a398
Create Date: 2025-09-18 18:36:25.513871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc4e3b4225a5'
down_revision: Union[str, Sequence[str], None] = 'b0a5a4d8a398'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Verificar si el tipo enum existe antes de crearlo
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'estado_institucion') THEN CREATE TYPE estado_institucion AS ENUM ('pendiente', 'activa', 'suspendida', 'inactiva'); END IF; END $$;")
    
    # Agregar las columnas a Institucion
    op.add_column('Institucion', sa.Column('estado', sa.Enum('pendiente', 'activa', 'suspendida', 'inactiva', name='estado_institucion'), server_default='pendiente', nullable=False))
    op.add_column('Institucion', sa.Column('fecha_creacion', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('Institucion', sa.Column('fecha_activacion', sa.TIMESTAMP(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Eliminar las columnas de Institucion
    op.drop_column('Institucion', 'fecha_activacion')
    op.drop_column('Institucion', 'fecha_creacion')
    op.drop_column('Institucion', 'estado')
    
    # No eliminamos el tipo enum porque podría estar en uso en otras tablas
    # ### end Alembic commands ###
