"""init

Revision ID: 24f5baaf2c45
Revises: 
Create Date: 2025-09-08 17:14:04.047157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24f5baaf2c45'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ChatBot',
    sa.Column('chat_bot_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.TEXT(), nullable=False),
    sa.Column('foto_perfil_url', sa.TEXT(), nullable=False),
    sa.Column('activo', sa.BOOLEAN(), nullable=True),
    sa.Column('fecha_registro', sa.DATE(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('chat_bot_id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('FAQBot',
    sa.Column('faq_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('pregunta', sa.TEXT(), nullable=False),
    sa.Column('respuesta', sa.TEXT(), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('ultima_actualizacion', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('faq_id')
    )
    op.create_table('Insignia',
    sa.Column('insignia_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.TEXT(), nullable=True),
    sa.Column('imagen_url', sa.TEXT(), nullable=True),
    sa.Column('tipo', postgresql.ENUM('objetivo', 'calificacion', 'racha', 'manual', name='tipo_insignia'), server_default=sa.text("'manual'"), nullable=False),
    sa.Column('es_unica', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('insignia_id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('MaterialEducativo',
    sa.Column('material_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.TEXT(), nullable=True),
    sa.Column('tipo_material', postgresql.ENUM('pdf', 'video', 'audio', 'imagen', 'presentacion', 'documento', 'hoja_de_calculo', 'enlace', 'interactivo', 'codigo_fuente', 'otro', name='tipo_material_educativo'), nullable=False),
    sa.Column('url_archivo', sa.String(length=255), nullable=False),
    sa.Column('formato_archivo', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('material_id')
    )
    op.create_table('Plataforma',
    sa.Column('plataforma_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('url_base', sa.TEXT(), nullable=False),
    sa.Column('tipo_integracion', postgresql.ENUM('api', 'manual', 'embebido', 'otro', name='tipo_integracion_plataforma'), nullable=False),
    sa.Column('requiere_cuenta', sa.BOOLEAN(), nullable=False),
    sa.Column('es_gratuita', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('plataforma_id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('Recompensa',
    sa.Column('recompensa_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.TEXT(), nullable=True),
    sa.Column('costo_puntos', sa.INTEGER(), nullable=False),
    sa.Column('tipo', postgresql.ENUM('foto_perfil', 'foto_portada', 'estilo_chat', 'sticker', 'otro', name='tipo_recompensa_enum'), server_default=sa.text("'otro'"), nullable=False),
    sa.CheckConstraint('costo_puntos >= 0', name='check_costo_puntos_positivo'),
    sa.PrimaryKeyConstraint('recompensa_id')
    )
    op.create_table('Tema',
    sa.Column('tema_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('emoji', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('tema_id')
    )
    op.create_table('Usuario',
    sa.Column('usuario_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('correo_institucional', sa.String(length=100), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('tipo_documento', postgresql.ENUM('cc', 'ti', 'ce', name='tipo_documento_usuario'), nullable=False),
    sa.Column('numero_documento', sa.String(length=20), nullable=False),
    sa.Column('rol', postgresql.ENUM('administrador', 'coordinador', 'docente', 'estudiante', name='rol_usuario'), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('estado_cuenta', postgresql.ENUM('activo', 'inactivo', 'suspendido', 'eliminado', name='estado_cuenta_usuario'), server_default=sa.text("'activo'"), nullable=False),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ultimo_acceso', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('perfil_url', sa.TEXT(), nullable=True),
    sa.Column('portada_url', sa.TEXT(), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('descripcion', sa.TEXT(), nullable=True),
    sa.Column('email_verified', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False),
    sa.Column('failed_login_attempts', sa.SMALLINT(), server_default=sa.text('0'), nullable=False),
    sa.Column('locked_until', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('twofa_enabled', sa.BOOLEAN(), server_default=sa.text('false'), nullable=False),
    sa.Column('twofa_secret', sa.String(length=32), nullable=True),
    sa.CheckConstraint("(rol = 'administrador' AND username IS NOT NULL AND correo_institucional IS NULL) OR (rol <> 'administrador' AND correo_institucional IS NOT NULL AND username IS NULL)", name='chk_login'),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    op.create_index(op.f('ix_Usuario_correo_institucional'), 'Usuario', ['correo_institucional'], unique=True)
    op.create_index(op.f('ix_Usuario_numero_documento'), 'Usuario', ['numero_documento'], unique=False)
    op.create_index(op.f('ix_Usuario_username'), 'Usuario', ['username'], unique=True)
    op.create_index(op.f('ix_Usuario_usuario_id'), 'Usuario', ['usuario_id'], unique=False)
    op.create_table('AdministradorSistema',
    sa.Column('administrador_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['administrador_id'], ['Usuario.usuario_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('administrador_id')
    )
    op.create_table('Coordinador',
    sa.Column('coordinador_id', sa.UUID(), nullable=False),
    sa.Column('horario_atencion', sa.String(length=50), nullable=True),
    sa.Column('fecha_inicio_carrera', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['coordinador_id'], ['Usuario.usuario_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('coordinador_id')
    )
    op.create_table('Docente',
    sa.Column('docente_id', sa.UUID(), nullable=False),
    sa.Column('area_conocimiento', sa.String(length=50), nullable=False),
    sa.Column('fecha_vinculacion', sa.DATE(), nullable=False),
    sa.Column('tipo_vinculacion', postgresql.ENUM('planta', 'catedra', 'ocasional', 'visitante', 'honorario', name='tipo_vinculacion_institucion'), server_default=sa.text("'planta'"), nullable=False),
    sa.Column('titulo_academico', sa.String(length=50), nullable=True),
    sa.Column('horas_semanales', sa.SMALLINT(), nullable=True),
    sa.ForeignKeyConstraint(['docente_id'], ['Usuario.usuario_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('docente_id')
    )
    op.create_table('HistorialPuntos',
    sa.Column('historial_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('cambio', sa.INTEGER(), nullable=False),
    sa.Column('motivo', sa.TEXT(), nullable=True),
    sa.Column('fecha', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cambio <> 0'),
    sa.ForeignKeyConstraint(['usuario_id'], ['Usuario.usuario_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('historial_id')
    )
    op.create_table('OAuthProvider',
    sa.Column('oauth_provider_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('provider_email', sa.String(length=255), nullable=False),
    sa.Column('fecha_vinculacion', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['Usuario.usuario_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('oauth_provider_id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_provider_user')
    )
    op.create_table('TemaPersonalizado',
    sa.Column('tema_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tema_id'], ['Tema.tema_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['Usuario.usuario_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tema_id'),
    sa.UniqueConstraint('usuario_id', 'tema_id', name='uq_nombre_predefinido')
    )
    op.create_table('TemaPredefinido',
    sa.Column('tema_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tema_id'], ['Tema.tema_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tema_id'),
    sa.UniqueConstraint('tema_id')
    )
    op.create_table('UsuarioInsignia',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('insignia_id', sa.UUID(), nullable=False),
    sa.Column('otorgada_por', sa.UUID(), nullable=True),
    sa.Column('fecha_otorgada', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['insignia_id'], ['Insignia.insignia_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['otorgada_por'], ['Usuario.usuario_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['Usuario.usuario_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id', 'insignia_id')
    )
    op.create_table('UsuarioPuntos',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('puntos_acumulados', sa.INTEGER(), server_default=sa.text('0'), nullable=False),
    sa.Column('cambio', sa.INTEGER(), nullable=False),
    sa.Column('motivo', sa.TEXT(), nullable=True),
    sa.Column('fecha', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cambio <> 0'),
    sa.ForeignKeyConstraint(['usuario_id'], ['Usuario.usuario_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    op.create_table('UsuarioRecompensa',
    sa.Column('usuario_recompensa_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('recompensa_id', sa.UUID(), nullable=True),
    sa.Column('fecha_canje', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['recompensa_id'], ['Recompensa.recompensa_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['Usuario.usuario_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('usuario_recompensa_id')
    )
    op.create_table('Institucion',
    sa.Column('institucion_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('administrador_id_creador', sa.UUID(), nullable=True),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('sigla', sa.String(length=20), nullable=True),
    sa.Column('lema', sa.String(length=255), nullable=True),
    sa.Column('tipo_institucion', postgresql.ENUM('escuela', 'colegio', 'instituto', 'universidad', 'politecnico', 'centro_de_formacion', 'corporacion', 'fundacion', 'academia', name='tipo_institucion'), nullable=False),
    sa.Column('usa_programas', sa.BOOLEAN(), nullable=False),
    sa.Column('nivel_educativo', postgresql.ENUM('basica', 'media', 'tecnica', 'tecnologica', 'superior', name='nivel_educativo_institucion'), nullable=False),
    sa.Column('sector', postgresql.ENUM('publico', 'privado', name='sector_institucion'), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('pais', sa.String(length=100), nullable=False),
    sa.Column('correo_institucional', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('nit', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['administrador_id_creador'], ['AdministradorSistema.administrador_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('institucion_id'),
    sa.UniqueConstraint('correo_institucional'),
    sa.UniqueConstraint('nit'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('sigla')
    )
    op.create_table('EscalaCalificacion',
    sa.Column('escala_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('institucion_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('tipo', postgresql.ENUM('numerica', 'letras', 'cualitativa', name='tipo_escalafon'), nullable=False),
    sa.Column('min_valor', sa.NUMERIC(precision=5, scale=2), nullable=True),
    sa.Column('max_valor', sa.NUMERIC(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['institucion_id'], ['Institucion.institucion_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('escala_id')
    )
    op.create_table('InstitucionCoordinador',
    sa.Column('institucion_id', sa.UUID(), nullable=False),
    sa.Column('coordinador_id', sa.UUID(), nullable=False),
    sa.Column('fecha_asignacion', sa.DATE(), nullable=False),
    sa.Column('estado', postgresql.ENUM('activo', 'invitado', 'expirado', 'retirado', name='estado_coordinador'), server_default=sa.text("'activo'"), nullable=False),
    sa.ForeignKeyConstraint(['coordinador_id'], ['Coordinador.coordinador_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institucion_id'], ['Institucion.institucion_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('institucion_id', 'coordinador_id')
    )
    op.create_table('Programa',
    sa.Column('programa_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('institucion_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.TEXT(), nullable=True),
    sa.Column('nivel', postgresql.ENUM('basico', 'media', 'tecnico', 'tecnologico', 'profesional', 'especializacion', 'maestria', 'doctorado', 'otro', name='nivel_programa'), nullable=False),
    sa.Column('tipo', postgresql.ENUM('presencial', 'virtual', 'mixto', 'a_distancia', 'dual', 'por_ciclos', 'continuo', 'otro', name='tipo_programa'), nullable=False),
    sa.ForeignKeyConstraint(['institucion_id'], ['Institucion.institucion_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('programa_id'),
    sa.UniqueConstraint('institucion_id', 'nombre', name='uq_programa_nombre')
    )
    op.create_table('Curso',
    sa.Column('curso_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('institucion_id', sa.UUID(), nullable=False),
    sa.Column('coordinador_id', sa.UUID(), nullable=True),
    sa.Column('programa_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.TEXT(), nullable=True),
    sa.Column('modalidad', postgresql.ENUM('anual', 'semestral', 'trimestral', 'cuatrimestral', 'bimestral', 'mensual', 'modular', 'flexible', 'otro', name='modalidad_curso'), nullable=False),
    sa.Column('fecha_inicio', sa.DATE(), nullable=True),
    sa.Column('fecha_fin', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['coordinador_id'], ['Coordinador.coordinador_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institucion_id'], ['Institucion.institucion_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['programa_id'], ['Programa.programa_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('curso_id'),
    sa.UniqueConstraint('institucion_id', 'nombre', name='uq_curso_nombre')
    )
    op.create_table('Estudiante',
    sa.Column('estudiante_id', sa.UUID(), nullable=False),
    sa.Column('programa_id', sa.UUID(), nullable=True),
    sa.Column('fecha_ingreso', sa.DATE(), nullable=False),
    sa.Column('creditos_aprobados', sa.SMALLINT(), nullable=True),
    sa.Column('etapa_formativa', postgresql.ENUM('i', 'ii', 'iii', 'iv', 'v', 'vi', 'vii', 'viii', 'ix', 'x', 'xi', 'xii', name='etapa_formativa_estudiante'), server_default=sa.text("'i'"), nullable=False),
    sa.Column('promedio_acumulado', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['estudiante_id'], ['Usuario.usuario_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['programa_id'], ['Programa.programa_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('estudiante_id')
    )
    op.create_table('Grupo',
    sa.Column('grupo_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('programa_id', sa.UUID(), nullable=False),
    sa.Column('docente_tutor_id', sa.UUID(), nullable=True),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('jornada', postgresql.ENUM('manana', 'tarde', 'nocturna', name='jornada_grupo'), server_default=sa.text("'manana'"), nullable=False),
    sa.ForeignKeyConstraint(['docente_tutor_id'], ['Docente.docente_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['programa_id'], ['Programa.programa_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('grupo_id'),
    sa.UniqueConstraint('docente_tutor_id')
    )
    op.create_table('ValorCalificacion',
    sa.Column('valor_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('escala_id', sa.UUID(), nullable=False),
    sa.Column('valor', sa.String(length=10), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=True),
    sa.Column('orden', sa.SMALLINT(), nullable=True),
    sa.ForeignKeyConstraint(['escala_id'], ['EscalaCalificacion.escala_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('valor_id')
    )
    op.create_table('ChatGrupo',
    sa.Column('chat_grupo_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('grupo_id', sa.UUID(), nullable=False),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('descripcion', sa.TEXT(), nullable=True),
    sa.Column('foto_perfil', sa.TEXT(), nullable=True),
    sa.Column('permite_archivos', sa.BOOLEAN(), server_default=sa.text('true'), nullable=False),
    sa.Column('capacidad_almacenamiento', sa.INTEGER(), server_default=sa.text('52428800'), nullable=False),
    sa.Column('estado_chat', postgresql.ENUM('activo', 'archivado', 'eliminado', name='estado_chat_grupo'), server_default=sa.text("'activo'"), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['Grupo.grupo_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_grupo_id')
    )
    op.create_table('CursoDocente',
    sa.Column('curso_id', sa.UUID(), nullable=False),
    sa.Column('docente_id', sa.UUID(), nullable=False),
    sa.Column('fecha_asignada', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['Curso.curso_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['docente_id'], ['Docente.docente_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('curso_id', 'docente_id')
    )
    op.create_table('EstudianteGrupo',
    sa.Column('grupo_id', sa.UUID(), nullable=False),
    sa.Column('estudiante_id', sa.UUID(), nullable=False),
    sa.Column('fecha_vinculacion', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['estudiante_id'], ['Estudiante.estudiante_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grupo_id'], ['Grupo.grupo_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('grupo_id', 'estudiante_id')
    )
    op.create_table('GrupoCurso',
    sa.Column('grupo_curso_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('grupo_id', sa.UUID(), nullable=False),
    sa.Column('curso_id', sa.UUID(), nullable=False),
    sa.Column('docente_id', sa.UUID(), nullable=False),
    sa.Column('fecha_asignacion', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['Curso.curso_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['docente_id'], ['Docente.docente_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['grupo_id'], ['Grupo.grupo_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('grupo_curso_id'),
    sa.UniqueConstraint('curso_id', 'grupo_id', name='uq_grupo_curso')
    )
    op.create_table('MaterialCurso',
    sa.Column('material_curso_id', sa.UUID(), nullable=False),
    sa.Column('curso_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['Curso.curso_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['material_curso_id'], ['MaterialEducativo.material_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('material_curso_id', 'curso_id')
    )
    op.create_table('ArchivoChat',
    sa.Column('archivo_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('chat_grupo_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('nombre_archivo', sa.TEXT(), nullable=False),
    sa.Column('url_archivo', sa.TEXT(), nullable=False),
    sa.Column('fecha_envio', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tipo_archivo', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['chat_grupo_id'], ['ChatGrupo.chat_grupo_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['Usuario.usuario_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('archivo_id')
    )
    op.create_table('Clase',
    sa.Column('clase_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('grupo_curso_id', sa.UUID(), nullable=False),
    sa.Column('plataforma_id', sa.UUID(), nullable=True),
    sa.Column('titulo', sa.TEXT(), nullable=False),
    sa.Column('descripcion', sa.TEXT(), nullable=True),
    sa.Column('hora_inicio', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('duracion', postgresql.INTERVAL(), nullable=False),
    sa.Column('link_videollamada', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_curso_id'], ['GrupoCurso.grupo_curso_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plataforma_id'], ['Plataforma.plataforma_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('clase_id')
    )
    op.create_table('Mensaje',
    sa.Column('mensaje_id', sa.UUID(), nullable=False),
    sa.Column('chat_grupo_id', sa.UUID(), nullable=False),
    sa.Column('emisor_id', sa.UUID(), nullable=True),
    sa.Column('fecha_hora', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tipo', postgresql.ENUM('texto', 'archivo', 'imagen', 'audio', name='tipo_mensaje'), nullable=False),
    sa.Column('contenido', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['chat_grupo_id'], ['ChatGrupo.chat_grupo_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['emisor_id'], ['Usuario.usuario_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('mensaje_id')
    )
    op.create_table('Asistencia',
    sa.Column('asistencia_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('clase_id', sa.UUID(), nullable=False),
    sa.Column('estudiante_id', sa.UUID(), nullable=False),
    sa.Column('estado', postgresql.ENUM('presente', 'ausente', 'justificado', name='estado_asistencia'), nullable=False),
    sa.ForeignKeyConstraint(['clase_id'], ['Clase.clase_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['estudiante_id'], ['Estudiante.estudiante_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asistencia_id')
    )
    op.create_table('MaterialClase',
    sa.Column('material_clase_id', sa.UUID(), nullable=False),
    sa.Column('clase_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['clase_id'], ['Clase.clase_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['material_clase_id'], ['MaterialEducativo.material_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('material_clase_id')
    )
    op.create_table('Tarea',
    sa.Column('tarea_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('docente_id', sa.UUID(), nullable=True),
    sa.Column('clase_id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.TEXT(), nullable=True),
    sa.Column('fecha_asignacion', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_limite', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('archivo_adjunto', sa.TEXT(), nullable=True),
    sa.Column('permite_entregas_tardias', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['clase_id'], ['Clase.clase_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['docente_id'], ['Docente.docente_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('tarea_id')
    )
    op.create_table('EntregarTarea',
    sa.Column('entrega_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tarea_id', sa.UUID(), nullable=False),
    sa.Column('estudiante_id', sa.UUID(), nullable=False),
    sa.Column('archivo', sa.TEXT(), nullable=False),
    sa.Column('fecha_envio', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('calificacion', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('fecha_revision', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint('calificacion >= 0 AND calificacion <= 5', name='chk_calificacion'),
    sa.ForeignKeyConstraint(['estudiante_id'], ['Estudiante.estudiante_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tarea_id'], ['Tarea.tarea_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entrega_id'),
    sa.UniqueConstraint('tarea_id', 'estudiante_id', name='uq_entrega')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('EntregarTarea')
    op.drop_table('Tarea')
    op.drop_table('MaterialClase')
    op.drop_table('Asistencia')
    op.drop_table('Mensaje')
    op.drop_table('Clase')
    op.drop_table('ArchivoChat')
    op.drop_table('MaterialCurso')
    op.drop_table('GrupoCurso')
    op.drop_table('EstudianteGrupo')
    op.drop_table('CursoDocente')
    op.drop_table('ChatGrupo')
    op.drop_table('ValorCalificacion')
    op.drop_table('Grupo')
    op.drop_table('Estudiante')
    op.drop_table('Curso')
    op.drop_table('Programa')
    op.drop_table('InstitucionCoordinador')
    op.drop_table('EscalaCalificacion')
    op.drop_table('Institucion')
    op.drop_table('UsuarioRecompensa')
    op.drop_table('UsuarioPuntos')
    op.drop_table('UsuarioInsignia')
    op.drop_table('TemaPredefinido')
    op.drop_table('TemaPersonalizado')
    op.drop_table('OAuthProvider')
    op.drop_table('HistorialPuntos')
    op.drop_table('Docente')
    op.drop_table('Coordinador')
    op.drop_table('AdministradorSistema')
    op.drop_index(op.f('ix_Usuario_usuario_id'), table_name='Usuario')
    op.drop_index(op.f('ix_Usuario_username'), table_name='Usuario')
    op.drop_index(op.f('ix_Usuario_numero_documento'), table_name='Usuario')
    op.drop_index(op.f('ix_Usuario_correo_institucional'), table_name='Usuario')
    op.drop_table('Usuario')
    op.drop_table('Tema')
    op.drop_table('Recompensa')
    op.drop_table('Plataforma')
    op.drop_table('MaterialEducativo')
    op.drop_table('Insignia')
    op.drop_table('FAQBot')
    op.drop_table('ChatBot')
    # ### end Alembic commands ###
