"""Add Reacciones table

Revision ID: 9f8e5d4c3b2a
Revises: fc4e3b4225a5
Create Date: 2025-09-30 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9f8e5d4c3b2a'
down_revision = 'fc4e3b4225a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Reacciones',
        sa.Column('reaccion_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('comentario_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('usuario_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('emoji', sa.String(length=10), nullable=False),
        sa.Column('tipo', sa.String(length=20), nullable=True),
        sa.Column('fecha_creacion', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
        sa.ForeignKeyConstraint(['comentario_id'], ['Comentario.comentario_id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['usuario_id'], ['Usuario.usuario_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('reaccion_id'),
        # Evitar que un usuario reaccione múltiples veces con el mismo emoji al mismo comentario
        sa.UniqueConstraint('comentario_id', 'usuario_id', 'emoji', name='uq_user_emoji_per_comment')
    )
    
    # Agregar índices para mejorar performance
    op.create_index('idx_reacciones_comentario_id', 'Reacciones', ['comentario_id'])
    op.create_index('idx_reacciones_usuario_id', 'Reacciones', ['usuario_id'])
    op.create_index('idx_reacciones_emoji', 'Reacciones', ['emoji'])
    op.create_index('idx_reacciones_activo', 'Reacciones', ['activo'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_reacciones_activo', table_name='Reacciones')
    op.drop_index('idx_reacciones_emoji', table_name='Reacciones')
    op.drop_index('idx_reacciones_usuario_id', table_name='Reacciones')
    op.drop_index('idx_reacciones_comentario_id', table_name='Reacciones')
    op.drop_table('Reacciones')
    # ### end Alembic commands ###